// Hand-curated franchise all-time starting 5s for the most storied
// franchises. Coverage is deliberately narrow — 10 teams that produce
// the strongest five-name lineups in pickup-game arguments. Smaller-
// market teams without 5 clear hall-of-famers are skipped.
//
// personId 0 means we don't have a CDN-hosted headshot for that player
// — the UI degrades to text-only attribution (no broken image).

export interface FranchiseFiveEntry {
  personId: number;
  name: string;
  position: "G" | "F" | "C";   // simplified — many played multiple
  era: string;                  // "1984-1998"
  // One-liner shown in tooltip / under name
  bio: string;
  bioZh?: string;
  // Career trophy summary used for prestige sorting in UI
  rings?: number;
  mvps?: number;
}

export interface FranchiseFive {
  tricode: string;
  // 5 starters, in canonical PG → C order when possible
  five: FranchiseFiveEntry[];
}

export const FRANCHISE_FIVE: FranchiseFive[] = [
  {
    tricode: "LAL",
    five: [
      { personId: 77142, name: "Magic Johnson", position: "G", era: "1979-1996",
        bio: "Showtime era PG — 5 rings, 3 MVPs, 3 FMVPs.",
        bioZh: "Showtime 时代控卫 — 5 冠 3 MVP 3 FMVP。",
        rings: 5, mvps: 3 },
      { personId: 977, name: "Kobe Bryant", position: "G", era: "1996-2016",
        bio: "20-year Laker. 5 rings, 81-point game, 2 FMVPs.",
        bioZh: "20 年湖人。5 冠、81 分单场、2 FMVP。",
        rings: 5, mvps: 1 },
      { personId: 2544, name: "LeBron James", position: "F", era: "2018-",
        bio: "Brought the 2020 bubble title to LA. Career arc capstone.",
        bioZh: "2020 园区冠军带回洛杉矶。",
        rings: 1, mvps: 0 },
      { personId: 76246, name: "Elgin Baylor", position: "F", era: "1958-1971",
        bio: "Pre-merger superstar — 27 PPG over a 14-year career.",
        bioZh: "联盟合并前的超巨 — 14 年职业生涯场均 27 分。",
        rings: 0 },
      { personId: 76003, name: "Kareem Abdul-Jabbar", position: "C", era: "1975-1989",
        bio: "Skyhook era — 38,387 career points held the all-time mark for 39 years.",
        bioZh: "天勾时代 — 38,387 分历史得分纪录保持 39 年。",
        rings: 5, mvps: 3 },
    ],
  },
  {
    tricode: "BOS",
    five: [
      { personId: 304, name: "Bob Cousy", position: "G", era: "1950-1963",
        bio: "Original ball-handling magician. 6 rings.",
        bioZh: "最早的运球大师，6 冠。",
        rings: 6 },
      { personId: 0, name: "Sam Jones", position: "G", era: "1957-1969",
        bio: "10 rings as a Celtics guard — third-most in NBA history.",
        bioZh: "凯尔特人后卫 10 冠 — NBA 第三多。",
        rings: 10 },
      { personId: 1449, name: "Larry Bird", position: "F", era: "1979-1992",
        bio: "3 MVPs, 3 rings, 2 FMVPs — defined the '80s rivalry.",
        bioZh: "3 MVP 3 冠 2 FMVP — 定义了 80 年代的对抗。",
        rings: 3, mvps: 3 },
      { personId: 708, name: "Kevin Garnett", position: "F", era: "2007-2013",
        bio: "Brought intensity + DPOY pedigree; key to 2008 title.",
        bioZh: "防守强度 + DPOY 履历，2008 夺冠核心。",
        rings: 1 },
      { personId: 78049, name: "Bill Russell", position: "C", era: "1956-1969",
        bio: "11 rings in 13 seasons — most NBA championships ever.",
        bioZh: "13 个赛季 11 冠 — NBA 史上最多。",
        rings: 11, mvps: 5 },
    ],
  },
  {
    tricode: "CHI",
    five: [
      { personId: 0, name: "Derrick Rose", position: "G", era: "2008-2016",
        bio: "Youngest MVP ever (22). Hometown hero.",
        bioZh: "22 岁 — 史上最年轻 MVP。",
        rings: 0, mvps: 1 },
      { personId: 893, name: "Michael Jordan", position: "G", era: "1984-1998",
        bio: "6 rings, 6 FMVPs, 5 MVPs, 10 scoring titles. The argument-ender.",
        bioZh: "6 冠 6 FMVP 5 MVP 10 个得分王。一锤定音的存在。",
        rings: 6, mvps: 5 },
      { personId: 0, name: "Scottie Pippen", position: "F", era: "1987-1998",
        bio: "MJ's running mate. Top-50 all-time, 6 rings.",
        bioZh: "乔丹的搭档。历史前 50，6 冠。",
        rings: 6 },
      { personId: 0, name: "Horace Grant", position: "F", era: "1987-1994",
        bio: "Glue forward on the first three-peat.",
        bioZh: "第一个三连冠的胶水型大前。",
        rings: 3 },
      { personId: 0, name: "Artis Gilmore", position: "C", era: "1976-1982",
        bio: "ABA legacy carried over — 17 PPG / 11 RPG as a Bull.",
        bioZh: "ABA 传奇身份继承到 NBA — 公牛时期场均 17/11。",
        rings: 0 },
    ],
  },
  {
    tricode: "GSW",
    five: [
      { personId: 201939, name: "Stephen Curry", position: "G", era: "2009-",
        bio: "4 rings, 2 MVPs (one unanimous), all-time 3PT leader.",
        bioZh: "4 冠 2 MVP（一次全票）— 三分历史第一人。",
        rings: 4, mvps: 2 },
      { personId: 202691, name: "Klay Thompson", position: "G", era: "2011-2024",
        bio: "Splash Bro #2 — 4 rings, 60 in 29 min, 37-point quarter.",
        bioZh: "水花二号 — 4 冠、29 分钟 60 分、单节 37 分纪录。",
        rings: 4 },
      { personId: 201142, name: "Kevin Durant", position: "F", era: "2016-2019",
        bio: "Tipped a dynasty over the edge. 2 rings + 2 FMVPs in 3 years.",
        bioZh: "把王朝推上巅峰。3 年 2 冠 2 FMVP。",
        rings: 2 },
      { personId: 0, name: "Rick Barry", position: "F", era: "1965-1980",
        bio: "Underhand free throws and a 1975 title-and-FMVP run.",
        bioZh: "反手罚球 + 1975 年冠军 + FMVP。",
        rings: 1 },
      { personId: 0, name: "Wilt Chamberlain", position: "C", era: "1959-1965 (SF/PHI)",
        bio: "Played his peak SF Warriors years here — 50.4 PPG season.",
        bioZh: "巅峰旧金山勇士时代在这 — 场均 50.4 分赛季。",
        rings: 0 },
    ],
  },
  {
    tricode: "SAS",
    five: [
      { personId: 0, name: "Tony Parker", position: "G", era: "2001-2018",
        bio: "Floater-king PG. 4 rings + 2007 FMVP.",
        bioZh: "飘逸抛投控卫。4 冠 + 2007 FMVP。",
        rings: 4 },
      { personId: 0, name: "Manu Ginóbili", position: "G", era: "2002-2018",
        bio: "Sixth-man trailblazer — 4 rings, 2 All-Stars, HoF.",
        bioZh: "第六人开创者 — 4 冠 + 2 全明星 + 名人堂。",
        rings: 4 },
      { personId: 0, name: "George Gervin", position: "G", era: "1976-1985",
        bio: "Iceman finger-roll era — 4 scoring titles.",
        bioZh: "Iceman 抠手指上篮时代 — 4 个得分王。",
        rings: 0 },
      { personId: 401, name: "David Robinson", position: "C", era: "1989-2003",
        bio: "Admiral. 1995 MVP, 2 rings, DPOY pedigree.",
        bioZh: "海军上将。1995 MVP，2 冠，DPOY。",
        rings: 2, mvps: 1 },
      { personId: 1495, name: "Tim Duncan", position: "C", era: "1997-2016",
        bio: "Big Fundamental — 5 rings, 2 MVPs, 3 FMVPs, foundation of the modern Spurs.",
        bioZh: "石佛 — 5 冠 2 MVP 3 FMVP，现代马刺的奠基者。",
        rings: 5, mvps: 2 },
    ],
  },
  {
    tricode: "MIA",
    five: [
      { personId: 0, name: "Tim Hardaway", position: "G", era: "1996-2001",
        bio: "UTEP-step crossover originator.",
        bioZh: "经典的 UTEP 双重交叉的发明者。",
      },
      { personId: 2548, name: "Dwyane Wade", position: "G", era: "2003-2019",
        bio: "Franchise icon. 3 rings, 2006 FMVP, 13 All-Stars.",
        bioZh: "球队 GOAT — 3 冠、2006 FMVP、13 个全明星。",
        rings: 3 },
      { personId: 2544, name: "LeBron James", position: "F", era: "2010-2014",
        bio: "Heatles run — 2 rings, 2 MVPs, 2 FMVPs in 4 years.",
        bioZh: "热火三巨头 — 4 年 2 冠 2 MVP 2 FMVP。",
        rings: 2, mvps: 2 },
      { personId: 0, name: "Chris Bosh", position: "F", era: "2010-2017",
        bio: "Stretch-5 evolution prototype. 2 rings.",
        bioZh: "Stretch-5 进化的原型。2 冠。",
        rings: 2 },
      { personId: 0, name: "Alonzo Mourning", position: "C", era: "1995-2008",
        bio: "Defensive anchor. 2 DPOYs, 2006 ring.",
        bioZh: "防守支柱。2 DPOY，2006 夺冠。",
        rings: 1 },
    ],
  },
  {
    tricode: "DET",
    five: [
      { personId: 0, name: "Isiah Thomas", position: "G", era: "1981-1994",
        bio: "Bad Boys leader. 2 rings, 1990 FMVP.",
        bioZh: "坏孩子军团领袖。2 冠 + 1990 FMVP。",
        rings: 2 },
      { personId: 0, name: "Joe Dumars", position: "G", era: "1985-1999",
        bio: "Defensive ace + 1989 FMVP. 2 rings.",
        bioZh: "防守王 + 1989 FMVP。2 冠。",
        rings: 2 },
      { personId: 0, name: "Grant Hill", position: "F", era: "1994-2000",
        bio: "MJ-as-Forward prototype before injuries.",
        bioZh: "伤病前曾被誉为「下一个乔丹」的全能锋线。",
      },
      { personId: 0, name: "Bill Laimbeer", position: "F", era: "1982-1993",
        bio: "Bad Boy enforcer + 4 All-Stars.",
        bioZh: "坏孩子核心硬汉，4 个全明星。",
        rings: 2 },
      { personId: 235, name: "Dennis Rodman", position: "F", era: "1986-1993",
        bio: "Two-time DPOY in Detroit. Eventually 5 rings.",
        bioZh: "活塞时期两届 DPOY，最终生涯 5 冠。",
        rings: 2 },
    ],
  },
  {
    tricode: "PHI",
    five: [
      { personId: 947, name: "Allen Iverson", position: "G", era: "1996-2006",
        bio: "MVP at 6 feet. 4 scoring titles.",
        bioZh: "182 cm 的 MVP，4 个得分王。",
        mvps: 1 },
      { personId: 0, name: "Hal Greer", position: "G", era: "1958-1973",
        bio: "10× All-Star, 1967 ring.",
        bioZh: "10 次全明星，1967 冠军。",
        rings: 1 },
      { personId: 0, name: "Julius Erving", position: "F", era: "1976-1987",
        bio: "Dr J — popularized above-the-rim NBA, 1983 ring.",
        bioZh: "J 博士 — 推广了 NBA 的飞翔风格，1983 夺冠。",
        rings: 1, mvps: 1 },
      { personId: 203954, name: "Joel Embiid", position: "C", era: "2014-",
        bio: "2023 MVP + 2 scoring titles.",
        bioZh: "2023 MVP + 2 个得分王。",
        mvps: 1 },
      { personId: 76375, name: "Wilt Chamberlain", position: "C", era: "1965-1968 (PHI)",
        bio: "1967 ring with the 76ers. The 100-point game was as a Warrior, but PHI got peak Wilt.",
        bioZh: "76 人时期 1967 夺冠。100 分是勇士时代，76 人才是巅峰。",
        rings: 1, mvps: 2 },
    ],
  },
  {
    tricode: "HOU",
    five: [
      { personId: 0, name: "Calvin Murphy", position: "G", era: "1970-1983",
        bio: "Tiny scorer (5'9\") with a 17-PPG career and HoF nod.",
        bioZh: "175cm 的得分手，生涯场均 17，名人堂。",
      },
      { personId: 201935, name: "James Harden", position: "G", era: "2012-2020",
        bio: "MVP + 3 straight scoring titles + step-back signature.",
        bioZh: "MVP + 连续 3 个得分王 + 后撤步签名动作。",
        mvps: 1 },
      { personId: 0, name: "Yao Ming", position: "C", era: "2002-2011",
        bio: "Globalized the NBA. 8 All-Stars in injury-shortened career.",
        bioZh: "推动了 NBA 全球化。伤病困扰的生涯里 8 个全明星。",
      },
      { personId: 165, name: "Hakeem Olajuwon", position: "C", era: "1984-2001",
        bio: "Dream Shake. 2 rings, MVP+DPOY+FMVP in 1994.",
        bioZh: "梦幻脚步 — 2 冠，1994 MVP+DPOY+FMVP。",
        rings: 2, mvps: 1 },
      { personId: 0, name: "Moses Malone", position: "C", era: "1976-1982",
        bio: "Houston launched his MVP-MVP-FMVP three-peat.",
        bioZh: "休城启动了他 MVP-MVP-FMVP 三连。",
        mvps: 2 },
    ],
  },
  {
    tricode: "NYK",
    five: [
      { personId: 0, name: "Walt Frazier", position: "G", era: "1967-1977",
        bio: "Clyde — 2 rings, signature in 1970 G7.",
        bioZh: "Clyde — 2 冠，1970 年 G7 教科书表现。",
        rings: 2 },
      { personId: 0, name: "Bernard King", position: "F", era: "1982-1987",
        bio: "Scoring champ. 1984 playoff legend.",
        bioZh: "得分王。1984 季后赛的传奇之夜。",
      },
      { personId: 0, name: "Willis Reed", position: "C", era: "1964-1974",
        bio: "MVP + 1970 G7 limped onto the floor — defining Knicks moment.",
        bioZh: "MVP + 1970 G7 跛行上场 — 尼克斯标志性时刻。",
        rings: 2, mvps: 1 },
      { personId: 122, name: "Patrick Ewing", position: "C", era: "1985-2000",
        bio: "Face of the '90s Knicks. 11 All-Stars, never a ring.",
        bioZh: "90 年代尼克斯门面。11 全明星，遗憾无冠。",
      },
      { personId: 0, name: "Earl Monroe", position: "G", era: "1971-1980",
        bio: "Pearl — joined Clyde to claim the '73 title.",
        bioZh: "Pearl — 与 Clyde 组合拿下 1973 年总冠军。",
        rings: 1 },
    ],
  },
];

export function getFranchiseFive(tricode: string): FranchiseFive | undefined {
  return FRANCHISE_FIVE.find((f) => f.tricode === tricode);
}
