// Hand-curated franchise all-time starting 5s for the most storied
// franchises. Coverage is deliberately narrow — 10 teams that produce
// the strongest five-name lineups in pickup-game arguments. Smaller-
// market teams without 5 clear hall-of-famers are skipped.
//
// personId 0 means we don't have a CDN-hosted headshot for that player
// — the UI degrades to text-only attribution (no broken image).

export interface FranchiseFiveEntry {
  personId: number;
  name: string;
  position: "G" | "F" | "C";   // simplified — many played multiple
  era: string;                  // "1984-1998"
  // One-liner shown in tooltip / under name
  bio: string;
  bioZh?: string;
  // Career trophy summary used for prestige sorting in UI
  rings?: number;
  mvps?: number;
}

export interface FranchiseFive {
  tricode: string;
  // 5 starters, in canonical PG → C order when possible
  five: FranchiseFiveEntry[];
}

export const FRANCHISE_FIVE: FranchiseFive[] = [
  {
    tricode: "LAL",
    five: [
      { personId: 77142, name: "Magic Johnson", position: "G", era: "1979-1996",
        bio: "Showtime era PG — 5 rings, 3 MVPs, 3 FMVPs.",
        bioZh: "Showtime 时代控卫 — 5 冠 3 MVP 3 FMVP。",
        rings: 5, mvps: 3 },
      { personId: 977, name: "Kobe Bryant", position: "G", era: "1996-2016",
        bio: "20-year Laker. 5 rings, 81-point game, 2 FMVPs.",
        bioZh: "20 年湖人。5 冠、81 分单场、2 FMVP。",
        rings: 5, mvps: 1 },
      { personId: 2544, name: "LeBron James", position: "F", era: "2018-",
        bio: "Brought the 2020 bubble title to LA. Career arc capstone.",
        bioZh: "2020 园区冠军带回洛杉矶。",
        rings: 1, mvps: 0 },
      { personId: 76246, name: "Elgin Baylor", position: "F", era: "1958-1971",
        bio: "Pre-merger superstar — 27 PPG over a 14-year career.",
        bioZh: "联盟合并前的超巨 — 14 年职业生涯场均 27 分。",
        rings: 0 },
      { personId: 76003, name: "Kareem Abdul-Jabbar", position: "C", era: "1975-1989",
        bio: "Skyhook era — 38,387 career points held the all-time mark for 39 years.",
        bioZh: "天勾时代 — 38,387 分历史得分纪录保持 39 年。",
        rings: 5, mvps: 3 },
    ],
  },
  {
    tricode: "BOS",
    five: [
      { personId: 304, name: "Bob Cousy", position: "G", era: "1950-1963",
        bio: "Original ball-handling magician. 6 rings.",
        bioZh: "最早的运球大师，6 冠。",
        rings: 6 },
      { personId: 0, name: "Sam Jones", position: "G", era: "1957-1969",
        bio: "10 rings as a Celtics guard — third-most in NBA history.",
        bioZh: "凯尔特人后卫 10 冠 — NBA 第三多。",
        rings: 10 },
      { personId: 1449, name: "Larry Bird", position: "F", era: "1979-1992",
        bio: "3 MVPs, 3 rings, 2 FMVPs — defined the '80s rivalry.",
        bioZh: "3 MVP 3 冠 2 FMVP — 定义了 80 年代的对抗。",
        rings: 3, mvps: 3 },
      { personId: 708, name: "Kevin Garnett", position: "F", era: "2007-2013",
        bio: "Brought intensity + DPOY pedigree; key to 2008 title.",
        bioZh: "防守强度 + DPOY 履历，2008 夺冠核心。",
        rings: 1 },
      { personId: 78049, name: "Bill Russell", position: "C", era: "1956-1969",
        bio: "11 rings in 13 seasons — most NBA championships ever.",
        bioZh: "13 个赛季 11 冠 — NBA 史上最多。",
        rings: 11, mvps: 5 },
    ],
  },
  {
    tricode: "CHI",
    five: [
      { personId: 0, name: "Derrick Rose", position: "G", era: "2008-2016",
        bio: "Youngest MVP ever (22). Hometown hero.",
        bioZh: "22 岁 — 史上最年轻 MVP。",
        rings: 0, mvps: 1 },
      { personId: 893, name: "Michael Jordan", position: "G", era: "1984-1998",
        bio: "6 rings, 6 FMVPs, 5 MVPs, 10 scoring titles. The argument-ender.",
        bioZh: "6 冠 6 FMVP 5 MVP 10 个得分王。一锤定音的存在。",
        rings: 6, mvps: 5 },
      { personId: 0, name: "Scottie Pippen", position: "F", era: "1987-1998",
        bio: "MJ's running mate. Top-50 all-time, 6 rings.",
        bioZh: "乔丹的搭档。历史前 50，6 冠。",
        rings: 6 },
      { personId: 0, name: "Horace Grant", position: "F", era: "1987-1994",
        bio: "Glue forward on the first three-peat.",
        bioZh: "第一个三连冠的胶水型大前。",
        rings: 3 },
      { personId: 0, name: "Artis Gilmore", position: "C", era: "1976-1982",
        bio: "ABA legacy carried over — 17 PPG / 11 RPG as a Bull.",
        bioZh: "ABA 传奇身份继承到 NBA — 公牛时期场均 17/11。",
        rings: 0 },
    ],
  },
  {
    tricode: "GSW",
    five: [
      { personId: 201939, name: "Stephen Curry", position: "G", era: "2009-",
        bio: "4 rings, 2 MVPs (one unanimous), all-time 3PT leader.",
        bioZh: "4 冠 2 MVP（一次全票）— 三分历史第一人。",
        rings: 4, mvps: 2 },
      { personId: 202691, name: "Klay Thompson", position: "G", era: "2011-2024",
        bio: "Splash Bro #2 — 4 rings, 60 in 29 min, 37-point quarter.",
        bioZh: "水花二号 — 4 冠、29 分钟 60 分、单节 37 分纪录。",
        rings: 4 },
      { personId: 201142, name: "Kevin Durant", position: "F", era: "2016-2019",
        bio: "Tipped a dynasty over the edge. 2 rings + 2 FMVPs in 3 years.",
        bioZh: "把王朝推上巅峰。3 年 2 冠 2 FMVP。",
        rings: 2 },
      { personId: 0, name: "Rick Barry", position: "F", era: "1965-1980",
        bio: "Underhand free throws and a 1975 title-and-FMVP run.",
        bioZh: "反手罚球 + 1975 年冠军 + FMVP。",
        rings: 1 },
      { personId: 0, name: "Wilt Chamberlain", position: "C", era: "1959-1965 (SF/PHI)",
        bio: "Played his peak SF Warriors years here — 50.4 PPG season.",
        bioZh: "巅峰旧金山勇士时代在这 — 场均 50.4 分赛季。",
        rings: 0 },
    ],
  },
  {
    tricode: "SAS",
    five: [
      { personId: 0, name: "Tony Parker", position: "G", era: "2001-2018",
        bio: "Floater-king PG. 4 rings + 2007 FMVP.",
        bioZh: "飘逸抛投控卫。4 冠 + 2007 FMVP。",
        rings: 4 },
      { personId: 0, name: "Manu Ginóbili", position: "G", era: "2002-2018",
        bio: "Sixth-man trailblazer — 4 rings, 2 All-Stars, HoF.",
        bioZh: "第六人开创者 — 4 冠 + 2 全明星 + 名人堂。",
        rings: 4 },
      { personId: 0, name: "George Gervin", position: "G", era: "1976-1985",
        bio: "Iceman finger-roll era — 4 scoring titles.",
        bioZh: "Iceman 抠手指上篮时代 — 4 个得分王。",
        rings: 0 },
      { personId: 401, name: "David Robinson", position: "C", era: "1989-2003",
        bio: "Admiral. 1995 MVP, 2 rings, DPOY pedigree.",
        bioZh: "海军上将。1995 MVP，2 冠，DPOY。",
        rings: 2, mvps: 1 },
      { personId: 1495, name: "Tim Duncan", position: "C", era: "1997-2016",
        bio: "Big Fundamental — 5 rings, 2 MVPs, 3 FMVPs, foundation of the modern Spurs.",
        bioZh: "石佛 — 5 冠 2 MVP 3 FMVP，现代马刺的奠基者。",
        rings: 5, mvps: 2 },
    ],
  },
  {
    tricode: "MIA",
    five: [
      { personId: 0, name: "Tim Hardaway", position: "G", era: "1996-2001",
        bio: "UTEP-step crossover originator.",
        bioZh: "经典的 UTEP 双重交叉的发明者。",
      },
      { personId: 2548, name: "Dwyane Wade", position: "G", era: "2003-2019",
        bio: "Franchise icon. 3 rings, 2006 FMVP, 13 All-Stars.",
        bioZh: "球队 GOAT — 3 冠、2006 FMVP、13 个全明星。",
        rings: 3 },
      { personId: 2544, name: "LeBron James", position: "F", era: "2010-2014",
        bio: "Heatles run — 2 rings, 2 MVPs, 2 FMVPs in 4 years.",
        bioZh: "热火三巨头 — 4 年 2 冠 2 MVP 2 FMVP。",
        rings: 2, mvps: 2 },
      { personId: 0, name: "Chris Bosh", position: "F", era: "2010-2017",
        bio: "Stretch-5 evolution prototype. 2 rings.",
        bioZh: "Stretch-5 进化的原型。2 冠。",
        rings: 2 },
      { personId: 0, name: "Alonzo Mourning", position: "C", era: "1995-2008",
        bio: "Defensive anchor. 2 DPOYs, 2006 ring.",
        bioZh: "防守支柱。2 DPOY，2006 夺冠。",
        rings: 1 },
    ],
  },
  {
    tricode: "DET",
    five: [
      { personId: 0, name: "Isiah Thomas", position: "G", era: "1981-1994",
        bio: "Bad Boys leader. 2 rings, 1990 FMVP.",
        bioZh: "坏孩子军团领袖。2 冠 + 1990 FMVP。",
        rings: 2 },
      { personId: 0, name: "Joe Dumars", position: "G", era: "1985-1999",
        bio: "Defensive ace + 1989 FMVP. 2 rings.",
        bioZh: "防守王 + 1989 FMVP。2 冠。",
        rings: 2 },
      { personId: 0, name: "Grant Hill", position: "F", era: "1994-2000",
        bio: "MJ-as-Forward prototype before injuries.",
        bioZh: "伤病前曾被誉为「下一个乔丹」的全能锋线。",
      },
      { personId: 0, name: "Bill Laimbeer", position: "F", era: "1982-1993",
        bio: "Bad Boy enforcer + 4 All-Stars.",
        bioZh: "坏孩子核心硬汉，4 个全明星。",
        rings: 2 },
      { personId: 235, name: "Dennis Rodman", position: "F", era: "1986-1993",
        bio: "Two-time DPOY in Detroit. Eventually 5 rings.",
        bioZh: "活塞时期两届 DPOY，最终生涯 5 冠。",
        rings: 2 },
    ],
  },
  {
    tricode: "PHI",
    five: [
      { personId: 947, name: "Allen Iverson", position: "G", era: "1996-2006",
        bio: "MVP at 6 feet. 4 scoring titles.",
        bioZh: "182 cm 的 MVP，4 个得分王。",
        mvps: 1 },
      { personId: 0, name: "Hal Greer", position: "G", era: "1958-1973",
        bio: "10× All-Star, 1967 ring.",
        bioZh: "10 次全明星，1967 冠军。",
        rings: 1 },
      { personId: 0, name: "Julius Erving", position: "F", era: "1976-1987",
        bio: "Dr J — popularized above-the-rim NBA, 1983 ring.",
        bioZh: "J 博士 — 推广了 NBA 的飞翔风格，1983 夺冠。",
        rings: 1, mvps: 1 },
      { personId: 203954, name: "Joel Embiid", position: "C", era: "2014-",
        bio: "2023 MVP + 2 scoring titles.",
        bioZh: "2023 MVP + 2 个得分王。",
        mvps: 1 },
      { personId: 76375, name: "Wilt Chamberlain", position: "C", era: "1965-1968 (PHI)",
        bio: "1967 ring with the 76ers. The 100-point game was as a Warrior, but PHI got peak Wilt.",
        bioZh: "76 人时期 1967 夺冠。100 分是勇士时代，76 人才是巅峰。",
        rings: 1, mvps: 2 },
    ],
  },
  {
    tricode: "HOU",
    five: [
      { personId: 0, name: "Calvin Murphy", position: "G", era: "1970-1983",
        bio: "Tiny scorer (5'9\") with a 17-PPG career and HoF nod.",
        bioZh: "175cm 的得分手，生涯场均 17，名人堂。",
      },
      { personId: 201935, name: "James Harden", position: "G", era: "2012-2020",
        bio: "MVP + 3 straight scoring titles + step-back signature.",
        bioZh: "MVP + 连续 3 个得分王 + 后撤步签名动作。",
        mvps: 1 },
      { personId: 0, name: "Yao Ming", position: "C", era: "2002-2011",
        bio: "Globalized the NBA. 8 All-Stars in injury-shortened career.",
        bioZh: "推动了 NBA 全球化。伤病困扰的生涯里 8 个全明星。",
      },
      { personId: 165, name: "Hakeem Olajuwon", position: "C", era: "1984-2001",
        bio: "Dream Shake. 2 rings, MVP+DPOY+FMVP in 1994.",
        bioZh: "梦幻脚步 — 2 冠，1994 MVP+DPOY+FMVP。",
        rings: 2, mvps: 1 },
      { personId: 0, name: "Moses Malone", position: "C", era: "1976-1982",
        bio: "Houston launched his MVP-MVP-FMVP three-peat.",
        bioZh: "休城启动了他 MVP-MVP-FMVP 三连。",
        mvps: 2 },
    ],
  },
  {
    tricode: "NYK",
    five: [
      { personId: 0, name: "Walt Frazier", position: "G", era: "1967-1977",
        bio: "Clyde — 2 rings, signature in 1970 G7.",
        bioZh: "Clyde — 2 冠，1970 年 G7 教科书表现。",
        rings: 2 },
      { personId: 0, name: "Bernard King", position: "F", era: "1982-1987",
        bio: "Scoring champ. 1984 playoff legend.",
        bioZh: "得分王。1984 季后赛的传奇之夜。",
      },
      { personId: 0, name: "Willis Reed", position: "C", era: "1964-1974",
        bio: "MVP + 1970 G7 limped onto the floor — defining Knicks moment.",
        bioZh: "MVP + 1970 G7 跛行上场 — 尼克斯标志性时刻。",
        rings: 2, mvps: 1 },
      { personId: 122, name: "Patrick Ewing", position: "C", era: "1985-2000",
        bio: "Face of the '90s Knicks. 11 All-Stars, never a ring.",
        bioZh: "90 年代尼克斯门面。11 全明星，遗憾无冠。",
      },
      { personId: 0, name: "Earl Monroe", position: "G", era: "1971-1980",
        bio: "Pearl — joined Clyde to claim the '73 title.",
        bioZh: "Pearl — 与 Clyde 组合拿下 1973 年总冠军。",
        rings: 1 },
    ],
  },
  {
    tricode: "UTA",
    five: [
      { personId: 304, name: "John Stockton", position: "G", era: "1984-2003",
        bio: "All-time assist + steal leader. Never traded.",
        bioZh: "历史助攻 + 抢断双料王。从未被交易过。",
      },
      { personId: 0, name: "Pete Maravich", position: "G", era: "1974-1980 (NOJ→UTA)",
        bio: "Pistol — 24 PPG career, dribbling magic ahead of his time.",
        bioZh: "Pistol — 生涯场均 24，超越时代的运球魔术。",
      },
      { personId: 252, name: "Karl Malone", position: "F", era: "1985-2003",
        bio: "Mailman. 2 MVPs, 36,928 career points (3rd all-time when he retired).",
        bioZh: "邮差。2 MVP，生涯 36,928 分（退役时历史第三）。",
        mvps: 2 },
      { personId: 0, name: "Andrei Kirilenko", position: "F", era: "2001-2011",
        bio: "AK-47 — versatile across all 5 stat lines.",
        bioZh: "AK-47 — 五项数据全能。",
      },
      { personId: 0, name: "Mark Eaton", position: "C", era: "1982-1993",
        bio: "2-time DPOY, 7'4\" rim protector. 3.5 BPG career.",
        bioZh: "2 届 DPOY，2.24m 护框者，生涯场均 3.5 盖帽。",
      },
    ],
  },
  {
    tricode: "PHX",
    five: [
      { personId: 959, name: "Steve Nash", position: "G", era: "2004-2012",
        bio: "Back-to-back MVPs (2005-06). 7 Seconds or Less era.",
        bioZh: "连续两届 MVP（2005-06）— 7 秒进攻时代。",
        mvps: 2 },
      { personId: 1626164, name: "Devin Booker", position: "G", era: "2015-",
        bio: "70-point game at 20. Finals run in 2021.",
        bioZh: "20 岁 70 分。2021 闯进总决赛。",
      },
      { personId: 901, name: "Charles Barkley", position: "F", era: "1992-1996",
        bio: "1993 MVP, took the Suns to the Finals.",
        bioZh: "1993 MVP — 带太阳杀进总决赛。",
        mvps: 1 },
      { personId: 0, name: "Connie Hawkins", position: "F", era: "1969-1973",
        bio: "Skywalker — ABA-era pioneer, HoF.",
        bioZh: "Skywalker — ABA 时代先驱，名人堂。",
      },
      { personId: 0, name: "Amar'e Stoudemire", position: "C", era: "2002-2010",
        bio: "Pick-and-roll terror with Nash.",
        bioZh: "和 Nash 的挡拆杀器。",
      },
    ],
  },
  {
    tricode: "MIL",
    five: [
      { personId: 203081, name: "Damian Lillard", position: "G", era: "2023-",
        bio: "Late-career joining for a title push.",
        bioZh: "生涯末期加盟冲冠。",
      },
      { personId: 0, name: "Sidney Moncrief", position: "G", era: "1979-1989",
        bio: "2-time DPOY, 5× All-Star, HoF.",
        bioZh: "2 届 DPOY，5 次全明星，名人堂。",
      },
      { personId: 203507, name: "Giannis Antetokounmpo", position: "F", era: "2013-",
        bio: "2 MVPs, 2021 ring, DPOY. Greek Freak era.",
        bioZh: "2 MVP，2021 夺冠，DPOY。希腊怪兽时代。",
        rings: 1, mvps: 2 },
      { personId: 0, name: "Bob Dandridge", position: "F", era: "1969-1977",
        bio: "Played the 1971 title with Kareem.",
        bioZh: "1971 年与贾巴尔合力夺冠。",
        rings: 1 },
      { personId: 76003, name: "Kareem Abdul-Jabbar", position: "C", era: "1969-1975",
        bio: "Drafted #1 by the Bucks. 1971 title + 3 MVPs in MIL.",
        bioZh: "首轮第一顺位被雄鹿选中。1971 夺冠 + 3 MVP 都是雄鹿时期。",
        rings: 1, mvps: 3 },
    ],
  },
  {
    tricode: "TOR",
    five: [
      { personId: 0, name: "Kyle Lowry", position: "G", era: "2012-2021",
        bio: "Heart of the 2019 title run. 6× All-Star as a Raptor.",
        bioZh: "2019 夺冠核心。猛龙时期 6 次全明星。",
        rings: 1 },
      { personId: 0, name: "DeMar DeRozan", position: "G", era: "2009-2018",
        bio: "Mid-range maestro. Franchise scoring leader.",
        bioZh: "中距离大师。队史得分王。",
      },
      { personId: 202695, name: "Kawhi Leonard", position: "F", era: "2018-2019",
        bio: "One year. Title + Finals MVP. Single-season folk hero.",
        bioZh: "一年时间。冠军 + FMVP。一季封神。",
        rings: 1 },
      { personId: 1713, name: "Vince Carter", position: "F", era: "1998-2004",
        bio: "Air Canada. Dunked over Frédéric Weis at Sydney 2000.",
        bioZh: "Air Canada。2000 悉尼奥运扣过 Weis 头顶。",
      },
      { personId: 0, name: "Chris Bosh", position: "C", era: "2003-2010",
        bio: "Pre-Heat Big Three foundation. 5× All-Star as a Raptor.",
        bioZh: "热火三巨头前 — 猛龙时期 5 次全明星。",
      },
    ],
  },
  {
    tricode: "DEN",
    five: [
      { personId: 0, name: "Alex English", position: "G", era: "1979-1990",
        bio: "21,000+ points, HoF. Most points in the 1980s.",
        bioZh: "21,000+ 得分，名人堂。80 年代得分总数第一。",
      },
      { personId: 0, name: "Carmelo Anthony", position: "F", era: "2003-2011",
        bio: "Drafted #3 in '03 (LeBron's class). Scoring artist.",
        bioZh: "2003 探花（与 LeBron 同届）。得分艺术家。",
      },
      { personId: 0, name: "Dan Issel", position: "F", era: "1975-1985 (incl. ABA)",
        bio: "27,000+ combined ABA + NBA points.",
        bioZh: "ABA + NBA 合计 27,000+ 得分。",
      },
      { personId: 203999, name: "Nikola Jokić", position: "C", era: "2015-",
        bio: "3 MVPs, 2023 ring + FMVP. The #41 pick of all time.",
        bioZh: "3 MVP，2023 夺冠 + FMVP。第 41 顺位的逆袭。",
        rings: 1, mvps: 3 },
      { personId: 0, name: "Dikembe Mutombo", position: "C", era: "1991-1996",
        bio: "Finger-wag rim protector. 1995 upset over #1 seed Seattle.",
        bioZh: "摇手指护框大师。1995 客场首轮淘汰头号种子超音速。",
      },
    ],
  },
  {
    tricode: "OKC",
    five: [
      { personId: 1628983, name: "Shai Gilgeous-Alexander", position: "G", era: "2019-",
        bio: "2024 scoring title, top-3 MVP finishes, 2025 title with the Thunder.",
        bioZh: "2024 得分王，多次 MVP 前三，2025 带雷霆夺冠。",
        rings: 1, mvps: 1 },
      { personId: 201566, name: "Russell Westbrook", position: "G", era: "2008-2019",
        bio: "2017 MVP, only triple-double season average since Oscar.",
        bioZh: "2017 MVP，自 Oscar 之后唯一场均三双。",
        mvps: 1 },
      { personId: 201142, name: "Kevin Durant", position: "F", era: "2007-2016",
        bio: "4 scoring titles in OKC. 2014 MVP.",
        bioZh: "雷霆时期 4 个得分王。2014 MVP。",
        mvps: 1 },
      { personId: 0, name: "Paul George", position: "F", era: "2017-2019",
        bio: "Brief but elite — 28 PPG, top-3 MVP in 2018-19.",
        bioZh: "短暂但顶级 — 场均 28，2018-19 MVP 前三。",
      },
      { personId: 0, name: "Gary Payton (SEA)", position: "G", era: "1990-2003 (SuperSonics era)",
        bio: "Pre-OKC era — DPOY + Olympic gold. Franchise carried over.",
        bioZh: "OKC 前身 SuperSonics 时期 — DPOY + 奥运冠军。",
      },
    ],
  },
  {
    tricode: "POR",
    five: [
      { personId: 0, name: "Clyde Drexler", position: "G", era: "1983-1995",
        bio: "Glide. 1992 Finals run + HoF.",
        bioZh: "Glide — 1992 总决赛 + 名人堂。",
      },
      { personId: 203081, name: "Damian Lillard", position: "G", era: "2012-2023",
        bio: "Franchise icon. Dame time, 71-point night, walk-off 3 over OKC.",
        bioZh: "球队 GOAT。Dame Time、71 分之夜、对 OKC 的压哨绝杀。",
      },
      { personId: 0, name: "LaMarcus Aldridge", position: "F", era: "2006-2015",
        bio: "Mid-range jumper era. 5× All-Star as a Blazer.",
        bioZh: "中投时代。开拓者时期 5 次全明星。",
      },
      { personId: 0, name: "Bill Walton", position: "C", era: "1974-1979",
        bio: "1977 ring + FMVP. 1978 MVP. Injuries cut him short.",
        bioZh: "1977 夺冠 + FMVP。1978 MVP。伤病阻断生涯。",
        rings: 1, mvps: 1 },
      { personId: 0, name: "Maurice Lucas", position: "F", era: "1976-1980",
        bio: "Bodyguard on the 1977 title team.",
        bioZh: "1977 冠军球队的肌肉前锋。",
        rings: 1 },
    ],
  },
  {
    tricode: "IND",
    five: [
      { personId: 397, name: "Reggie Miller", position: "G", era: "1987-2005",
        bio: "5× All-Star. 25,000 career points. Knicks-killer.",
        bioZh: "5 次全明星。生涯 25,000 分。尼克斯天敌。",
      },
      { personId: 0, name: "Jermaine O'Neal", position: "F", era: "2000-2008",
        bio: "6× All-Star in Indy. Brawl-era centerpiece.",
        bioZh: "印城时期 6 次全明星。「奥本山宫斗事件」核心。",
      },
      { personId: 0, name: "Paul George", position: "F", era: "2010-2017",
        bio: "MIP 2013. Brought Indy back to ECF.",
        bioZh: "2013 最进步球员。带印城重回东决。",
      },
      { personId: 0, name: "Mel Daniels", position: "F", era: "1968-1974 (ABA → NBA)",
        bio: "ABA legend, 7 All-Star ABA selections, 3 titles.",
        bioZh: "ABA 传奇，7 届 ABA 全明星，3 冠。",
      },
      { personId: 0, name: "Rik Smits", position: "C", era: "1988-2000",
        bio: "Dunking Dutchman. Anchored Reggie-era Pacers.",
        bioZh: "扣篮荷兰人。Reggie 时代的内线支柱。",
      },
    ],
  },
  {
    tricode: "MEM",
    five: [
      { personId: 0, name: "Mike Conley", position: "G", era: "2007-2019",
        bio: "Grit-and-Grind floor general. Franchise wins leader.",
        bioZh: "Grit-and-Grind 时代的指挥官。队史胜场领袖。",
      },
      { personId: 0, name: "Ja Morant", position: "G", era: "2019-",
        bio: "Two-time All-Star. Most exciting under-30 in the modern game.",
        bioZh: "两次全明星。现代联盟最具观赏性的年轻人。",
      },
      { personId: 0, name: "Rudy Gay", position: "F", era: "2006-2013",
        bio: "Athletic wing scorer of the early Grizzlies.",
        bioZh: "灰熊早期的运动型锋线。",
      },
      { personId: 0, name: "Pau Gasol", position: "F", era: "2001-2008",
        bio: "ROY in '02, made Memphis a playoff team.",
        bioZh: "2002 最佳新秀，将灰熊带入季后赛。",
      },
      { personId: 0, name: "Marc Gasol", position: "C", era: "2008-2019",
        bio: "DPOY 2013, brother-vs-brother in NOLA.",
        bioZh: "2013 DPOY，兄弟对决的另一半。",
      },
    ],
  },
  {
    tricode: "CLE",
    five: [
      { personId: 0, name: "Mark Price", position: "G", era: "1986-1995",
        bio: "Sharpshooting PG. 90% career FT.",
        bioZh: "射手控卫。生涯罚球 90%。",
      },
      { personId: 1628378, name: "Donovan Mitchell", position: "G", era: "2022-",
        bio: "71-point night in 2023. All-Star yearly.",
        bioZh: "2023 单场 71 分。每年全明星。",
      },
      { personId: 2544, name: "LeBron James", position: "F", era: "2003-2010, 2014-2018",
        bio: "Two CLE stints. 2016 title — first in city's pro history.",
        bioZh: "两段骑士生涯。2016 夺冠 — 克利夫兰职业体育第一冠。",
        rings: 1, mvps: 4 },
      { personId: 0, name: "Kevin Love", position: "F", era: "2014-2022",
        bio: "Stretch-4 / outlet passer on the LeBron + Kyrie title team.",
        bioZh: "三分大前 / 长传专家 — LeBron + Kyrie 冠军班底。",
        rings: 1 },
      { personId: 0, name: "Brad Daugherty", position: "C", era: "1986-1994",
        bio: "5× All-Star center. Anchored '80s-'90s contenders.",
        bioZh: "5 次全明星中锋。80-90 年代核心。",
      },
    ],
  },
];

export function getFranchiseFive(tricode: string): FranchiseFive | undefined {
  return FRANCHISE_FIVE.find((f) => f.tricode === tricode);
}
