import { createHash } from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { getPlayerSeasonHeatmapCatalog } from "./season-heatmap-catalog-server";
import { decodeSeasonHeatmapResource } from "./season-heatmap-client";
import { decodeSeasonShotMapResource } from "./season-shot-map-client";
import { GET as heatmapGet } from "@/app/api/player-season-heatmap/route";
import { GET as spatialGet } from "@/app/api/player-season-shot-map/route";
import type { HeatmapIdentity } from "./season-heatmap";

// Independently replayed from all 18 pinned early-era CSVs, not generated by
// the production importer. Four shooting counts and source game counts also
// agree with the separately captured StatMuse season tables. This is secondary
// corroboration, not an official NBA completeness claim.
// Source revision: e829d4678be1e075f99e5d41a1c5f97089be446b.
const expected = [
  {
    "season": "1996-97",
    "seasonType": "Regular Season",
    "totals": {
      "fgm": 920,
      "fga": 1892,
      "fg3m": 111,
      "fg3a": 297
    },
    "shotBearingGames": 82,
    "plotted": {
      "fgm": 920,
      "fga": 1886,
      "fg3m": 111,
      "fg3a": 291
    },
    "residuals": [
      {
        "reason": "coordinate-shot-type-conflict",
        "fgm": 0,
        "fga": 6,
        "fg3m": 0,
        "fg3a": 6
      }
    ],
    "origin": {
      "fgm": 192,
      "fga": 368,
      "fg3m": 0,
      "fg3a": 6
    }
  },
  {
    "season": "1997-98",
    "seasonType": "Regular Season",
    "totals": {
      "fgm": 881,
      "fga": 1893,
      "fg3m": 30,
      "fg3a": 126
    },
    "shotBearingGames": 82,
    "plotted": {
      "fgm": 881,
      "fga": 1892,
      "fg3m": 30,
      "fg3a": 125
    },
    "residuals": [
      {
        "reason": "backcourt",
        "fgm": 0,
        "fga": 1,
        "fg3m": 0,
        "fg3a": 1
      }
    ],
    "origin": {
      "fgm": 244,
      "fga": 391,
      "fg3m": 0,
      "fg3a": 0
    }
  },
  {
    "season": "2001-02",
    "seasonType": "Regular Season",
    "totals": {
      "fgm": 551,
      "fga": 1324,
      "fg3m": 10,
      "fg3a": 53
    },
    "shotBearingGames": 60,
    "plotted": {
      "fgm": 551,
      "fga": 1324,
      "fg3m": 10,
      "fg3a": 53
    },
    "residuals": [],
    "origin": {
      "fgm": 32,
      "fga": 61,
      "fg3m": 0,
      "fg3a": 0
    }
  },
  {
    "season": "2002-03",
    "seasonType": "Regular Season",
    "totals": {
      "fgm": 679,
      "fga": 1527,
      "fg3m": 16,
      "fg3a": 55
    },
    "shotBearingGames": 82,
    "plotted": {
      "fgm": 679,
      "fga": 1527,
      "fg3m": 16,
      "fg3a": 55
    },
    "residuals": [],
    "origin": {
      "fgm": 56,
      "fga": 109,
      "fg3m": 0,
      "fg3a": 0
    }
  },
  {
    "season": "1996-97",
    "seasonType": "Playoffs",
    "totals": {
      "fgm": 227,
      "fga": 498,
      "fg3m": 13,
      "fg3a": 67
    },
    "shotBearingGames": 19,
    "plotted": {
      "fgm": 227,
      "fga": 498,
      "fg3m": 13,
      "fg3a": 67
    },
    "residuals": [],
    "origin": {
      "fgm": 63,
      "fga": 105,
      "fg3m": 0,
      "fg3a": 0
    }
  },
  {
    "season": "1997-98",
    "seasonType": "Playoffs",
    "totals": {
      "fgm": 243,
      "fga": 526,
      "fg3m": 13,
      "fg3a": 43
    },
    "shotBearingGames": 21,
    "plotted": {
      "fgm": 243,
      "fga": 526,
      "fg3m": 13,
      "fg3a": 43
    },
    "residuals": [],
    "origin": {
      "fgm": 81,
      "fga": 122,
      "fg3m": 0,
      "fg3a": 0
    }
  }
] as const;
// Independent raw-CSV cells, including the same-cell league reference.
const expectedBinHashes: Record<string, Record<string, string>> = {
  "1996-97:Regular Season": {
    "fine": "c213ea150c597b426bd0a1921fe7e1f75fe937337ec9f4f03eeb6c32874bf885",
    "coarse": "c65c3ddbe73385bc277b911570f5213e9895aa82b9ac54b47bd89d50895e338a"
  },
  "1997-98:Regular Season": {
    "fine": "e94621df55e0061bc8dc6180f02cbe16eca5985769a2f35bf59fbf7f4390d7cb",
    "coarse": "0c259044ff2046578d1a14b613de8cff769d8612ad2f10c44877949939c595e8"
  },
  "2001-02:Regular Season": {
    "fine": "73ee2b6c73b12a37f333597b2aa6ac63a2c329cc44dba40b58b402beb071f0a5",
    "coarse": "3c782aafd1de65d76692dbb74e64addbcdc86ee74bf0665ceaa5c8f21ac4f74f"
  },
  "2002-03:Regular Season": {
    "fine": "e704c94f181eb3026ce186e1c9845b7c7c2f9ad487ddcc798cc1c6ab3e30cd38",
    "coarse": "8947f8f16a281dc0cb2f694a2a217cba3dd78aa8bfa0967d2b93799bd68dcaea"
  },
  "1996-97:Playoffs": {
    "fine": "9e6256e94c33d9916f8e9b99064e69a05e6fc73b30e78c653d3966d676d85537",
    "coarse": "a3fd5648642fedb47ddc15e625ac36b8c65043090fc2e197695a3ab75a8cd363"
  },
  "1997-98:Playoffs": {
    "fine": "0fbaaeb3bf3619e0438864bb8f28535d2a14c38eca60320ba811d8793a9f6b54",
    "coarse": "554eb2035b4c40c3edc2129dae146daea6e213256ab53f59634774f5a48dee8a"
  }
};
const countKeys = ["fgm", "fga", "fg3m", "fg3a"] as const;
const identityOf = (entry: (typeof expected)[number]): HeatmapIdentity => ({ playerId: 893, season: entry.season, seasonType: entry.seasonType });
const request = (identity: HeatmapIdentity, spatial: boolean) => {
  const query = new URLSearchParams({ playerId: String(identity.playerId), season: identity.season, seasonType: identity.seasonType,
    geometry: spatial ? "nba-shot-hex-v1" : "nba-court-basic12-v1" });
  return new Request(`https://example.test/api/player-season-${spatial ? "shot-map" : "heatmap"}?${query}`);
};
afterEach(() => vi.restoreAllMocks());

describe("independent Jordan early-era shot regressions", () => {
  it("publishes exactly four regular seasons and two playoff datasets, totaling 7,660 source attempts", async () => {
    const catalog = await getPlayerSeasonHeatmapCatalog(893);
    expect(catalog).toHaveLength(6);
    expect(catalog.map(row => `${row.season}:${row.seasonType}`).sort()).toEqual(expected.map(row => `${row.season}:${row.seasonType}`).sort());
    expect(catalog.every(row => row.playerId === 893 && row.availability === "available")).toBe(true);
    expect(expected.reduce((total, row) => total + row.totals.fga, 0)).toBe(7660);
  });

  it.each(expected)("serves $season $seasonType with exact independently audited counts and coordinates", async entry => {
    const fetchSpy = vi.spyOn(globalThis, "fetch");
    const identity = identityOf(entry);
    const heatmapResponse = await heatmapGet(request(identity, false));
    expect(heatmapResponse.status).toBe(200);
    expect(heatmapResponse.headers.get("cache-control")).toBe("public, max-age=3600, s-maxage=86400");
    const heatmapRaw = await heatmapResponse.json();
    const heatmap = decodeSeasonHeatmapResource(heatmapRaw, identity);
    expect(heatmap.status).toBe("ready");
    if (heatmap.status !== "ready") throw new Error(`Missing court data for ${entry.season}/${entry.seasonType}`);
    expect(heatmap.data.totals).toEqual({ fgm: entry.totals.fgm, fga: entry.totals.fga });
    expect(heatmap.data.archive).toMatchObject({ fg3m: entry.totals.fg3m, fg3a: entry.totals.fg3a,
      shotBearingGames: entry.shotBearingGames, officialGp: null, officialControl: null,
      coverageStatus: "not-officially-reconciled" });
    expect(heatmap.data.source?.url).toContain("/e829d4678be1e075f99e5d41a1c5f97089be446b/datasets/shotdetail_");
    for (const key of countKeys) {
      expect([...heatmap.data.zones, ...heatmap.data.residuals].reduce((sum, row) => sum + (row[key] ?? 0), 0)).toBe(entry.totals[key]);
    }

    const mapResponse = await spatialGet(request(identity, true));
    expect(mapResponse.status).toBe(200);
    expect(mapResponse.headers.get("cache-control")).toBe("public, max-age=3600, s-maxage=86400");
    const mapRaw = await mapResponse.json();
    const map = decodeSeasonShotMapResource(mapRaw, identity);
    expect(map.status).toBe("ready");
    if (map.status !== "ready") throw new Error(`Missing spatial data for ${entry.season}/${entry.seasonType}`);
    expect(map.data.totals).toEqual(entry.totals);
    expect(map.data.plotted).toEqual(entry.plotted);
    expect(map.data.residuals).toEqual(entry.residuals);
    expect(map.data.resolutions.map(grid => [grid.id, grid.radius])).toEqual([["fine", 25], ["coarse", 40]]);
    for (const grid of map.data.resolutions) {
      expect(grid.bins.length).toBeGreaterThan(0);
      expect(grid.bins.length).toBeLessThanOrEqual(400);
      const cells = grid.bins.map(bin => [bin.q, bin.r, bin.fgm, bin.fga, bin.fg3m, bin.fg3a,
        bin.league.fgm, bin.league.fga, bin.league.fg3m, bin.league.fg3a]);
      expect(createHash("sha256").update(JSON.stringify(cells)).digest("hex"))
        .toBe(expectedBinHashes[`${entry.season}:${entry.seasonType}`][grid.id]);
      for (const key of countKeys) {
        expect(grid.bins.reduce((sum, bin) => sum + bin[key], 0)).toBe(entry.plotted[key]);
        expect(entry.plotted[key] + map.data.residuals.reduce((sum, residual) => sum + residual[key], 0)).toBe(entry.totals[key]);
      }
      // Keep literal two-point source zeros at the basket. Only explicit
      // three-point zero-coordinate conflicts leave the spatial plot.
      const origin = grid.bins.find(bin => bin.q === 0 && bin.r === 0);
      expect(origin).toBeDefined();
      expect(origin!.fgm).toBeGreaterThanOrEqual(entry.origin.fgm - entry.origin.fg3m);
      expect(origin!.fga).toBeGreaterThanOrEqual(entry.origin.fga - entry.origin.fg3a);
      for (const bin of grid.bins) {
        for (const key of countKeys) expect(bin.league[key]).toBeGreaterThanOrEqual(bin[key]);
      }
    }
    expect(JSON.stringify(mapRaw)).not.toMatch(/sourceZoneCounts|evidencePath|sourceSha256|\/workspace\/|"players"|"names"|generatingCode/);
    expect(Buffer.byteLength(JSON.stringify(mapRaw))).toBeLessThanOrEqual(128 * 1024);
    expect(fetchSpy).not.toHaveBeenCalled();
  });

  it.each([
    ["1987-88", "Regular Season"], ["1995-96", "Regular Season"], ["1995-96", "Playoffs"],
    ["1998-99", "Regular Season"], ["1999-00", "Regular Season"], ["2000-01", "Regular Season"],
    ["2001-02", "Playoffs"], ["2002-03", "Playoffs"], ["2003-04", "Regular Season"],
  ] as const)("keeps absent Jordan records unavailable for %s %s", async (season, seasonType) => {
    const identity: HeatmapIdentity = { playerId: 893, season, seasonType };
    for (const spatial of [false, true]) {
      const response = await (spatial ? spatialGet : heatmapGet)(request(identity, spatial));
      expect(response.status).toBe(404);
      expect(response.headers.get("cache-control")).toBe("no-store");
      expect(await response.json()).toEqual({ status: "unavailable" });
    }
  });
});
