import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {beforeEach,expect,it,vi} from 'vitest';
import en from '@/locales/en';
import zh from '@/locales/zh';
const s=vi.hoisted(()=>({locale:'en',result:{} as Record<string,unknown>,career:vi.fn()}));
vi.mock('@/lib/usePlayerCareer',()=>({usePlayerCareer:(...args:unknown[])=>{s.career(...args);return s.result;}}));
vi.mock('@/components/LocaleProvider',()=>({useLocale:()=>({locale:s.locale,t:s.locale==='zh'?zh:en})}));
vi.mock('@/app/lab/career-arc/PlayerPicker',()=>({default:()=>null}));
vi.mock('@/app/lab/career-arc/CareerTrendChart',()=>({default:({seasons}:{seasons:{SEASON_ID:string}[]})=>createElement('div',null,seasons.map(row=>row.SEASON_ID).join(','))}));
vi.mock('@/app/lab/career-arc/CareerCourt',()=>({default:()=>null}));
import CareerArc from '@/app/lab/career-arc/CareerArc';
const row={SEASON_ID:'2025-26',TEAM_ABBREVIATION:'LAL',GP:70,MIN:30,PTS:20,REB:5,AST:6,STL:1,BLK:0,FG_PCT:.5,FG3_PCT:null,FT_PCT:.8};
const render=()=>renderToStaticMarkup(createElement(CareerArc,{playerId:2544,playerName:'LeBron James',teamTricode:'LAL'}));
beforeEach(()=>{s.career.mockClear();s.result={data:null,loading:false,error:false,stale:false,retry:vi.fn()};});
it.each(['en','zh'])('unavailable and genuine empty remain distinct%s',locale=>{s.locale=locale;s.result.error=true;expect(render()).toContain(locale==='zh'?'暂时无法加载':'Couldn&#x27;t load');s.result={...s.result,error:false,data:{careerSeasons:[]}};expect(render()).toContain(locale==='zh'?'数据源已响应':'The source responded');expect(s.career).toHaveBeenCalledWith(2544,'LeBron James','LAL');});
it.each(['en','zh'])('shared last-good data survives failedrefresh with visible warning%s',locale=>{s.locale=locale;s.result={...s.result,data:{careerSeasons:[row]},error:true,stale:true};const html=render();expect(html).toContain('2025-26');expect(html).toContain(locale==='zh'?'保留上次成功加载':'last successfully loaded');});
it('latest season selected by default and unknown percentages are not0',()=>{s.locale='en';s.result.data={careerSeasons:[{...row,SEASON_ID:'2024-25'},row]};const html=render();expect(html).toContain('value="1"');expect(html).toContain('—');});
it('loading with existing rows retains data rather than reverting to blank skeleton',()=>{s.result={...s.result,loading:true,stale:true,data:{careerSeasons:[row]}};expect(render()).toContain('2025-26');});
