// Colloquial / nickname → real player name fragments for search.
// Each entry's key (lowercased) is the alias; the value is a token that
// will match the player's `lastName` or `firstName lastName` field via the
// existing `.includes()` matcher in /api/search.

export const PLAYER_ALIASES: Record<string, string> = {
  // Active superstars — English nicknames
  "king james": "lebron james",
  "the king": "lebron james",
  "lbj": "lebron james",
  "greek freak": "antetokounmpo",
  "the greek freak": "antetokounmpo",
  "giannis": "antetokounmpo",
  "joker": "jokic",
  "the joker": "jokic",
  "the beard": "harden",
  "kd": "durant",
  "easy money sniper": "durant",
  "slim reaper": "durant",
  "steph": "curry",
  "chef curry": "curry",
  "dame": "lillard",
  "dame time": "lillard",
  "the brow": "davis",
  "ad": "anthony davis",
  "klay": "thompson",
  "kawhi": "leonard",
  "the claw": "leonard",
  "kyrie": "irving",
  "uncle drew": "irving",
  "luka": "doncic",
  "the don": "doncic",
  "spida": "mitchell",
  "spider": "mitchell",
  "cp3": "chris paul",
  "the point god": "chris paul",
  "russ": "westbrook",
  "brodie": "westbrook",
  "embiid": "embiid",
  "the process": "embiid",
  "jb": "jaylen brown",
  "jt": "jayson tatum",
  "sga": "shai",
  "shai": "shai gilgeous",
  "ja": "ja morant",
  "scoot": "henderson",
  "wemby": "wembanyama",
  "victor": "wembanyama",
  "chet": "holmgren",
  "paolo": "banchero",

  // Legends (still searchable via playerIndex toYear/fromYear)
  "his airness": "michael jordan",
  "mj": "michael jordan",
  "goat": "michael jordan",
  "the mailman": "malone",
  "the worm": "rodman",
  "magic": "johnson",
  "bird": "larry bird",
  "the answer": "iverson",
  "ai": "iverson",
  "kobe": "bryant",
  "mamba": "bryant",
  "the black mamba": "bryant",
  "shaq": "o'neal",
  "the diesel": "o'neal",
  "the big fundamental": "duncan",
  "td": "duncan",
  "agent zero": "arenas",
  "vince": "vince carter",
  "vinsanity": "carter",
  "manu": "ginobili",
  "the big ticket": "garnett",
  "kg": "garnett",
  "the truth": "pierce",
  "d-wade": "wade",
  "dwade": "wade",
  "flash": "wade",
  "amare": "stoudemire",
  "z-bo": "randolph",
  "jr smith": "earl smith",

  // Chinese nicknames (most common Hupu/CN basketball community terms)
  "詹姆斯": "lebron james",
  "老詹": "lebron james",
  "勒布朗": "lebron james",
  "字母哥": "antetokounmpo",
  "约基奇": "jokic",
  "大胡子": "harden",
  "哈登": "harden",
  "杜兰特": "durant",
  "阿杜": "durant",
  "kd35": "durant",
  "库里": "curry",
  "萌神": "curry",
  "利拉德": "lillard",
  "浓眉": "anthony davis",
  "戴维斯": "anthony davis",
  "克莱": "thompson",
  "汤普森": "thompson",
  "莱昂纳德": "leonard",
  "可兰白克": "leonard",
  "卡哇伊": "leonard",
  "欧文": "irving",
  "厄文": "irving",
  "东契奇": "doncic",
  "卢卡": "doncic",
  "保罗": "chris paul",
  "韦少": "westbrook",
  "威少": "westbrook",
  "恩比德": "embiid",
  "大帝": "embiid",
  "塔图姆": "tatum",
  "杰伦布朗": "jaylen brown",
  "亚历山大": "shai",
  "莫兰特": "morant",
  "文班亚马": "wembanyama",
  "文班": "wembanyama",
  "霍尔姆格伦": "holmgren",
  "班凯罗": "banchero",
  "乔丹": "michael jordan",
  "篮球之神": "michael jordan",
  "马龙": "malone",
  "罗德曼": "rodman",
  "魔术师": "magic johnson",
  "拉里伯德": "larry bird",
  "大鸟": "larry bird",
  "艾弗森": "iverson",
  "答案": "iverson",
  "科比": "bryant",
  "曼巴": "bryant",
  "黑曼巴": "bryant",
  "奥尼尔": "o'neal",
  "大鲨鱼": "o'neal",
  "邓肯": "duncan",
  "石佛": "duncan",
  "卡特": "vince carter",
  "半人半神": "vince carter",
  "吉诺比利": "ginobili",
  "妖刀": "ginobili",
  "加内特": "garnett",
  "狼王": "garnett",
  "皮尔斯": "pierce",
  "真理": "pierce",
  "韦德": "wade",
  "闪电侠": "wade",
};

// Resolve any number of aliases against a lowercased query. Returns the
// expanded query terms (original + alias targets) so the matcher can OR
// across them.
export function expandQuery(qLower: string): string[] {
  const expansions = new Set<string>();
  expansions.add(qLower);
  // exact alias match
  const exact = PLAYER_ALIASES[qLower];
  if (exact) expansions.add(exact);
  // partial — try each alias key as a substring of the query
  for (const key of Object.keys(PLAYER_ALIASES)) {
    if (qLower.includes(key)) expansions.add(PLAYER_ALIASES[key]);
  }
  return [...expansions];
}
