// Colloquial / nickname → real player name fragments for search.
// Each entry's key (lowercased) is the alias; the value is a token that
// will match the player's `lastName` or `firstName lastName` field via the
// existing `.includes()` matcher in /api/search.

export const PLAYER_ALIASES: Record<string, string> = {
  // Active superstars — English nicknames
  "king james": "lebron james",
  "the king": "lebron james",
  "lbj": "lebron james",
  "greek freak": "antetokounmpo",
  "the greek freak": "antetokounmpo",
  "giannis": "antetokounmpo",
  "joker": "jokic",
  "the joker": "jokic",
  "the beard": "harden",
  "kd": "durant",
  "easy money sniper": "durant",
  "slim reaper": "durant",
  "steph": "curry",
  "chef curry": "curry",
  "dame": "lillard",
  "dame time": "lillard",
  "the brow": "davis",
  "ad": "anthony davis",
  "klay": "thompson",
  "kawhi": "leonard",
  "the claw": "leonard",
  "kyrie": "irving",
  "uncle drew": "irving",
  "luka": "doncic",
  "the don": "doncic",
  "spida": "mitchell",
  "spider": "mitchell",
  "cp3": "chris paul",
  "the point god": "chris paul",
  "russ": "westbrook",
  "brodie": "westbrook",
  "embiid": "embiid",
  "the process": "embiid",
  "jb": "jaylen brown",
  "jt": "jayson tatum",
  "sga": "shai",
  "shai": "shai gilgeous",
  "ja": "ja morant",
  "scoot": "henderson",
  "wemby": "wembanyama",
  "victor": "wembanyama",
  "chet": "holmgren",
  "paolo": "banchero",

  // Legends (still searchable via playerIndex toYear/fromYear)
  "his airness": "michael jordan",
  "mj": "michael jordan",
  "goat": "michael jordan",
  "the mailman": "malone",
  "the worm": "rodman",
  "magic": "johnson",
  "bird": "larry bird",
  "the answer": "iverson",
  "ai": "iverson",
  "kobe": "bryant",
  "mamba": "bryant",
  "the black mamba": "bryant",
  "shaq": "o'neal",
  "the diesel": "o'neal",
  "the big fundamental": "duncan",
  "td": "duncan",
  "agent zero": "arenas",
  "vince": "vince carter",
  "vinsanity": "carter",
  "manu": "ginobili",
  "the big ticket": "garnett",
  "kg": "garnett",
  "the truth": "pierce",
  "d-wade": "wade",
  "dwade": "wade",
  "flash": "wade",
  "amare": "stoudemire",
  "z-bo": "randolph",
  "jr smith": "earl smith",

  // Chinese nicknames (most common Hupu/CN basketball community terms)
  "詹姆斯": "lebron james",
  "老詹": "lebron james",
  "勒布朗": "lebron james",
  "乐邦": "lebron james",
  "詹皇": "lebron james",
  "小皇帝": "lebron james",
  "皇帝": "lebron james",
  "字母哥": "antetokounmpo",
  "约基奇": "jokic",
  "大胡子": "harden",
  "哈登": "harden",
  "杜兰特": "durant",
  "阿杜": "durant",
  "kd35": "durant",
  "库里": "curry",
  "萌神": "curry",
  "利拉德": "lillard",
  "浓眉": "anthony davis",
  "戴维斯": "anthony davis",
  "克莱": "thompson",
  "汤普森": "thompson",
  "莱昂纳德": "leonard",
  "可兰白克": "leonard",
  "卡哇伊": "leonard",
  "欧文": "irving",
  "厄文": "irving",
  "东契奇": "doncic",
  "卢卡": "doncic",
  "保罗": "chris paul",
  "韦少": "westbrook",
  "威少": "westbrook",
  "恩比德": "embiid",
  "大帝": "embiid",
  "塔图姆": "tatum",
  "杰伦布朗": "jaylen brown",
  "亚历山大": "shai",
  "莫兰特": "morant",
  "文班亚马": "wembanyama",
  "文班": "wembanyama",
  "霍尔姆格伦": "holmgren",
  "班凯罗": "banchero",
  "乔丹": "michael jordan",
  "篮球之神": "michael jordan",
  "马龙": "malone",
  "罗德曼": "rodman",
  "魔术师": "magic johnson",
  "拉里伯德": "larry bird",
  "大鸟": "larry bird",
  "艾弗森": "iverson",
  "答案": "iverson",
  "科比": "bryant",
  "曼巴": "bryant",
  "黑曼巴": "bryant",
  "奥尼尔": "o'neal",
  "大鲨鱼": "o'neal",
  "邓肯": "duncan",
  "石佛": "duncan",
  "卡特": "vince carter",
  "半人半神": "vince carter",
  "吉诺比利": "ginobili",
  "妖刀": "ginobili",
  "加内特": "garnett",
  "狼王": "garnett",
  "皮尔斯": "pierce",
  "真理": "pierce",
  "韦德": "wade",
  "闪电侠": "wade",

  // International / modern era — English nicknames + native names
  "the slovenian sensation": "doncic",
  "el matador": "ginobili",
  "the brazilian blur": "leandro barbosa",
  "the dream": "olajuwon",
  "the admiral": "robinson",
  "the chief": "robert parish",
  "the round mound of rebound": "barkley",
  "sir charles": "barkley",
  "skywalker": "dominique wilkins",
  "the human highlight reel": "dominique wilkins",
  "rifleman": "chuck person",
  "starbury": "marbury",
  "yao": "yao ming",
  "yao ming": "yao ming",
  "yi": "jianlian",
  "jeremy lin": "lin",
  "linsanity": "jeremy lin",
  "manute": "bol",
  "muggsy": "bogues",
  "rik smits": "smits",
  "mutombo": "mutombo",
  "mt mutombo": "mutombo",
  "the goon": "rasheed wallace",
  "rasheed": "rasheed wallace",
  "diaw": "diaw",

  // 2020s active stars (more aliases)
  "jokić": "jokic",
  "the bosnian beast": "jusuf nurkic",
  "trout": "young",
  "ice trae": "trae young",
  "jt0": "jayson tatum",
  "max": "maxey",
  "tyrese maxey": "maxey",
  "tyrese haliburton": "haliburton",
  "halliburton": "haliburton",
  "hali": "haliburton",
  "edwards": "anthony edwards",
  "ant-man": "anthony edwards",
  "ant": "anthony edwards",
  "anthony edwards": "anthony edwards",
  "lamelo": "lamelo ball",
  "lamelo ball": "lamelo ball",
  "melo ball": "lamelo ball",
  "zion": "williamson",
  "zion williamson": "williamson",
  "the cleveland kid": "evan mobley",
  "mobley": "evan mobley",
  "scottie barnes": "barnes",
  "cade": "cunningham",
  "cade cunningham": "cunningham",
  "jalen brunson": "brunson",
  "deuce": "brunson",
  "deandre ayton": "ayton",
  "ayton": "ayton",
  "miles bridges": "miles bridges",
  "kawhi leonard": "leonard",
  "the klaw": "leonard",
  "the fun guy": "leonard",
  "rj barrett": "barrett",
  "barrett": "rj barrett",
  "fox": "deaaron fox",
  "deaaron fox": "deaaron fox",
  "swipa": "deaaron fox",
  "siakam": "siakam",
  "spicy p": "siakam",
  "vanvleet": "vanvleet",
  "steady freddie": "vanvleet",
  "fred vanvleet": "vanvleet",

  // Chinese — international players + modern stars
  "姚明": "yao ming",
  "易建联": "jianlian",
  "林书豪": "lin",
  "豪小子": "lin",
  "诺维茨基": "nowitzki",
  "司机": "nowitzki",
  "德克": "nowitzki",
  "纳什": "nash",
  "风之子": "nash",
  "麦迪": "tracy mcgrady",
  "麦蒂": "tracy mcgrady",
  "tmac": "tracy mcgrady",
  "tmcgrady": "tracy mcgrady",
  "佩顿": "gary payton",
  "手套": "gary payton",
  "斯托克顿": "stockton",
  "犹他双煞": "stockton",
  "皮蓬": "pippen",
  "二当家": "pippen",
  "罗斯": "derrick rose",
  "玫瑰": "derrick rose",
  "drose": "derrick rose",
  "hibbert": "hibbert",
  "诺阿": "joakim noah",
  "霍华德": "dwight howard",
  "魔兽": "dwight howard",
  "保罗加索尔": "pau gasol",
  "加索尔": "pau gasol",
  "甜瓜": "carmelo anthony",
  "梅隆": "carmelo anthony",
  "卡梅隆安东尼": "carmelo anthony",
  "卡梅罗": "carmelo anthony",
  "甜美": "carmelo anthony",
  "亚特兰大之子": "trae young",
  "崔阳": "trae young",
  "崔扬": "trae young",
  "崔少": "trae young",
  "蚂蚁": "anthony edwards",
  "安东尼爱德华兹": "anthony edwards",
  "球哥": "lonzo ball",
  "二球": "lamelo ball",
  "锡安": "williamson",
  "锡安威廉森": "williamson",
  "胖虎": "williamson",
  "莫布利": "evan mobley",
  "斯科蒂巴恩斯": "scottie barnes",
  "巴恩斯": "scottie barnes",
  "卡宁汉": "cade cunningham",
  "凯德": "cade cunningham",
  "布伦森": "brunson",
  "艾顿": "ayton",
  "福克斯": "deaaron fox",
  "西卡": "siakam",
  "锡卡": "siakam",
  "范弗利特": "vanvleet",
  "马克西": "maxey",
  "哈利伯顿": "haliburton",
  "小哈": "haliburton",
  "巴雷特": "barrett",
  "杨纳森": "wembanyama",
  "邓罗": "luke kennard",

  // Coaches / legends-as-coach references
  "禅师": "phil jackson",
  "phil jackson": "phil jackson",
  "波波": "popovich",
  "波波维奇": "popovich",
  "popovich": "popovich",
  "pop": "popovich",
};

// Resolve any number of aliases against a lowercased query. Returns the
// expanded query terms (original + alias targets) so the matcher can OR
// across them.
export function expandQuery(qLower: string): string[] {
  const expansions = new Set<string>();
  expansions.add(qLower);
  // exact alias match
  const exact = PLAYER_ALIASES[qLower];
  if (exact) expansions.add(exact);
  // partial — single-word ASCII keys must match a whole token: raw substring
  // matching made "james" hit "ja" (Morant) and "wade" hit "ad" (Davis).
  // CJK and multi-word keys keep substring semantics ("老詹比赛", "kd shot chart").
  const tokens = qLower.split(/\s+/);
  for (const key of Object.keys(PLAYER_ALIASES)) {
    const singleAsciiWord = !key.includes(" ") && /^[\x20-\x7e]+$/.test(key);
    const hit = singleAsciiWord ? tokens.includes(key) : qLower.includes(key);
    if (hit) expansions.add(PLAYER_ALIASES[key]);
  }
  return [...expansions];
}
