import{expect,it,vi}from'vitest';
import{runRecoveryChunks}from'./recovery-chunks';
import{createRecoveryProviderClient}from'./recovery-provider-client';
// Synthetic repeated-date fixtures exercise cache/budget mechanics only.
function fixture(count=40){const games=Array.from({length:count},(_,i)=>{const date=new Date(Date.UTC(2026,3,1+Math.floor(i/3))).toISOString().slice(0,10);return{gameId:`00425001${Math.floor(i/7)}${i%7+1}`,gameStatus:3,gameCode:`${date.replaceAll('-','')}/NYKSAS`,gameDateTimeUTC:`${date}T12:00:00Z`,homeTeam:{teamTricode:'SAS',score:100+i},awayTeam:{teamTricode:'NYK',score:90},uuid:`${(i+1).toString(16).padStart(8,'0')}-aaaa-4aaa-8aaa-aaaaaaaaaaaa`,date};});return{games,schedule:{dates:[{games}]}};}
function responseBody(points:number){return{meta:{available:true,players_available:true,team_stats_available:true,withheld:{players:0,team_stats:0}},data:{team_stats:[{team_name:'San Antonio Spurs'},{team_name:'New York Knicks'}],players:[points,90].map((pts,i)=>({name:`TEST ${i}`,stats:{...Object.fromEntries(['minutes','points','rebounds','assists','offensiveRebounds','defensiveRebounds','steals','blocks','turnovers','fouls','plusMinus'].map(k=>[k,{value:k==='points'?String(pts):'0'}])),starter:{value:'false'},'fieldGoalsMade-fieldGoalsAttempted':{value:'0-0'},'threePointFieldGoalsMade-threePointFieldGoalsAttem':{value:'0-0'},'freeThrowsMade-freeThrowsAttempted':{value:`${pts}-${pts}`}}}))}};}
function setup(count=40,max=120,reject=false){const f=fixture(count);const fetcher=vi.fn(async(input:string|URL|Request)=>{const url=new URL(String(input));if(url.pathname.endsWith('/stats')){const game=f.games.find(g=>url.pathname.includes(g.uuid))!;const body=responseBody(game.homeTeam.score);if(reject)body.meta.players_available=false;return new Response(JSON.stringify(body));}const date=url.searchParams.get('date');const data=f.games.filter(g=>g.date===date).map(g=>({id:g.uuid,sport:'basketball',league:'NBA',status:'finished',kickoff_utc:g.gameDateTimeUTC,home:{name:'San Antonio Spurs',short_name:'SA'},away:{name:'New York Knicks',short_name:'NY'},score:{home:g.homeTeam.score,away:90}}));return new Response(JSON.stringify({data,meta:{date_window:{date}},pagination:{total:data.length,offset:0,limit:100}}));});const client=createRecoveryProviderClient({apiKey:'TEST_ONLY',maxRequests:max,expiresAt:'2026-10-03T00:00:00Z',now:()=>Date.parse('2026-10-02T14:00:00Z'),fetcher});return{...f,fetcher,client};}
it('two20-target chunks share one counter and date-page cache, with no duplicate game',async()=>{const f=setup();const result=await runRecoveryChunks(f.schedule,new Set(),null,f.client,120,new Set(),new Map(),2);expect(result.accepted).toHaveLength(40);expect(new Set(result.accepted.map(g=>g.game.nbaGameId)).size).toBe(40);expect(result.rejected).toEqual([]);expect(result.requests).toBe(54);expect(f.fetcher).toHaveBeenCalledTimes(54);});
it('default daily operation remains one20-target chunk',async()=>{const f=setup();const result=await runRecoveryChunks(f.schedule,new Set(),null,f.client,120,new Set(),new Map());expect(result.accepted).toHaveLength(20);});
it('classified failures do not repeat within a small two-chunk run',async()=>{const f=setup(3,120,true);const result=await runRecoveryChunks(f.schedule,new Set(),null,f.client,120,new Set(),new Map(),2);expect(result.accepted).toEqual([]);expect(result.rejected).toHaveLength(3);expect(new Set(result.rejected.map(g=>g.gameId)).size).toBe(3);expect(result.requests).toBe(4);});
it('request exhaustion stops the next chunk and preserves only the last classified cursor',async()=>{const f=setup(40,5);const result=await runRecoveryChunks(f.schedule,new Set(),null,f.client,5,new Set(),new Map(),2);expect(result.requests).toBe(5);expect(f.fetcher).toHaveBeenCalledTimes(5);expect(result.accepted.length).toBeGreaterThan(0);expect(result.cursor).toBe(result.accepted.at(-1)!.game.nbaGameId);});
it('preexisting saved and strong games are never fetched again',async()=>{const f=setup(3);const saved=new Set([f.games[0].gameId]);const result=await runRecoveryChunks(f.schedule,saved,null,f.client,120,saved,new Map(),2);expect(result.accepted).toHaveLength(2);expect(result.accepted.some(g=>saved.has(g.game.nbaGameId))).toBe(false);expect(saved.size).toBe(1);});
it.each([0,3,-1,1.5])('rejects unbounded chunk count%s before requests',async chunks=>{const f=setup();await expect(runRecoveryChunks(f.schedule,new Set(),null,f.client,120,new Set(),new Map(),chunks)).rejects.toThrow('chunk count');expect(f.fetcher).not.toHaveBeenCalled();});
it('the second chunk cannot reset the shared120-second deadline',async()=>{const f=setup();let now=Date.parse('2026-10-02T14:00:00Z');const fetcher=vi.fn(async(input:string|URL|Request)=>{const response=await f.fetcher(input);if(f.fetcher.mock.calls.length===29)now+=121000;return response;});const client=createRecoveryProviderClient({apiKey:'TEST_ONLY',maxRequests:120,expiresAt:'2026-10-03T00:00:00Z',now:()=>now,fetcher});const result=await runRecoveryChunks(f.schedule,new Set(),null,client,120,new Set(),new Map(),2);expect(result.accepted).toHaveLength(20);expect(result.requests).toBe(29);expect(result.rejected.at(-1)?.reason).toContain('deadline');});
it('provider UUID ownership from the first chunk protects the second chunk',async()=>{const f=setup();const fetcher=vi.fn(async(input:string|URL|Request)=>{const url=new URL(String(input)),response=await f.fetcher(input);if(url.searchParams.get('date')!==f.games[19].date)return response;const body=await response.json();for(const row of body.data)if(row.score.home===f.games[19].homeTeam.score)row.id=f.games[39].uuid;return new Response(JSON.stringify(body));});const client=createRecoveryProviderClient({apiKey:'TEST_ONLY',maxRequests:120,expiresAt:'2026-10-03T00:00:00Z',now:()=>Date.parse('2026-10-02T14:00:00Z'),fetcher});const result=await runRecoveryChunks(f.schedule,new Set(),null,client,120,new Set(),new Map(),2);expect(result.accepted).toHaveLength(39);expect(result.rejected).toContainEqual({gameId:f.games[19].gameId,reason:'provider-match-already-assigned'});expect(result.accepted.filter(g=>g.game.providerMatchId===f.games[39].uuid)).toHaveLength(1);});
