import { readFileSync } from 'node:fs';
import { expect,it } from 'vitest';
// Existing ESLint dependency, no new package/tooling installation.
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const {load}=require('js-yaml') as {load:(text:string)=>Record<string,unknown>};
const text=readFileSync('.github/workflows/player-data-ingestion.yml','utf8');
const workflow=load(text) as {on:Record<string,unknown>;permissions:Record<string,unknown>;concurrency:{group:string;'cancel-in-progress':boolean};jobs:Record<string,{name:string;permissions:Record<string,string>;steps:Record<string,unknown>[];if:string}>};
it('only scheduled/operator entry and one serializedworkflow, neverPR-triggered credentials',()=>{expect(Object.keys(workflow.on).sort()).toEqual(['push','schedule','workflow_dispatch']);expect(workflow.concurrency).toEqual({group:'nba-provider-first-connectivity','cancel-in-progress':false});expect(workflow.permissions).toEqual({});});
it('quota has no providerkey orwritepermission; exactingestjob getsminimumapprovedpermissions',()=>{expect(workflow.jobs.quota.permissions).toEqual({contents:'read',actions:'read'});expect(JSON.stringify(workflow.jobs.quota)).not.toContain('BIGBALLSDATA_API_KEY');expect(workflow.jobs.ingest.name).toBe('Ingest player data');expect(workflow.jobs.ingest.permissions).toEqual({contents:'write',actions:'read'});expect(workflow.jobs.ingest.if).toContain("needs.quota.outputs.allowed == 'true'");});
it('providerkey is scoped only tofetchstep, neverlogs orURLs',()=>{const found=workflow.jobs.ingest.steps.filter(s=>JSON.stringify(s).includes('BIGBALLSDATA_API_KEY'));expect(found).toHaveLength(4);expect(found.map(s=>s.name)).toEqual(['Verify known provider snapshots','Diagnose one playoff metadata response','Restore one validated Finals player table','Fetch and normalize provider data']);expect(found.every(s=>typeof s.if==='string')).toBe(true);expect(text).not.toContain('set -x');expect(text).not.toContain('pull_request_target');expect(text).not.toContain('--force');});
it('actions are pinned anddatapublishallowlist excludescode, secrets andstrongersnapshots',()=>{for(const job of Object.values(workflow.jobs))for(const step of job.steps)if(step.uses)expect(String(step.uses)).toMatch(/^actions\/(checkout|setup-node)@[0-9a-f]{40}$/);const publish=workflow.jobs.ingest.steps.find(s=>s.name==='Publish one data-only commit without force')!;expect(publish.run).toContain('git add -- src/data/provider-player-boxes.json src/data/provider-recovery-state.json');expect(publish.run).not.toContain('recovered-player-boxes.json');expect(publish.run).toContain('git rev-parse origin/master');expect(publish.run).toContain('git push origin HEAD:master');});

it('one-off connectivity has no executable provider path or secret and shares serialization',()=>{const legacy=load(readFileSync('.github/workflows/verify-player-provider.yml','utf8')) as typeof workflow;expect(legacy.jobs.verify.if).toBe('${{ false }}');expect(JSON.stringify(legacy)).not.toContain('BIGBALLSDATA_API_KEY');expect(legacy.concurrency).toEqual(workflow.concurrency);});

it('diagnostic push is exact-path/master and only reaches a3-request readonly mode',()=>{expect(workflow.on.push).toEqual({branches:['master'],paths:['.github/recovery-kickoff/2026-10-02-restore-finals-sample.json']});const step=workflow.jobs.ingest.steps.find(s=>s.name==='Restore one validated Finals player table')!;expect(step.env).toMatchObject({RECOVERY_MODE:'restore',RECOVERY_REQUEST_LIMIT:'1'});const backfill=workflow.jobs.ingest.steps.find(s=>s.name==='Fetch and normalize provider data')!;expect(backfill.if).not.toContain("!= 'workflow_dispatch'");});
