import{expect,it,vi}from'vitest';
import schedule from'../data/schedule-2025-26.json';
import{createRecoveryProviderClient}from'./recovery-provider-client';
import{recoverFinalsSample,VERIFIED_FINALS_SAMPLE}from'./recovery-finals-sample';
// Numerically consistent SYNTHETIC parser fixtures, not real Finals player rows.
function body(){return{meta:{available:true,players_available:true,team_stats_available:true,withheld:{players:0,team_stats:3}},data:{team_stats:[{team_name:'San Antonio Spurs'},{team_name:'New York Knicks'}],players:[90,94].map((points,i)=>({name:`TEST player ${i}`,stats:{...Object.fromEntries(['minutes','points','rebounds','assists','offensiveRebounds','defensiveRebounds','steals','blocks','turnovers','fouls','plusMinus'].map(k=>[k,{value:k==='points'?String(points):'0'}])),starter:{value:'false'},'fieldGoalsMade-fieldGoalsAttempted':{value:'0-0'},'threePointFieldGoalsMade-threePointFieldGoalsAttem':{value:'0-0'},'freeThrowsMade-freeThrowsAttempted':{value:`${points}-${points}`}}}))}};}
function client(raw=body()){const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify(raw)));return{fetcher,value:createRecoveryProviderClient({apiKey:'TEST_ONLY',maxRequests:1,expiresAt:'2026-10-03T00:00:00Z',now:()=>Date.parse('2026-10-02T13:00:00Z'),fetcher})};}
it('uses exactly one previously identity-verified endpoint and validates complete player module',async()=>{const c=client();const r=await recoverFinalsSample(schedule,c.value,new Set());expect(c.fetcher).toHaveBeenCalledTimes(1);expect(String(c.fetcher.mock.calls[0][0])).toBe(`https://api.bigballsdata.com/v1/stored/matches/${VERIFIED_FINALS_SAMPLE.providerMatchId}/stats`);expect(r).toMatchObject({requests:1,cursor:null,rejected:[]});expect(r.accepted).toHaveLength(1);expect(r.accepted[0].game).toMatchObject({nbaGameId:'0042500405',home:{tricode:'SAS',score:90},away:{tricode:'NYK',score:94}});expect(r.accepted[0].players.every(p=>p.team===null)).toBe(true);expect(r.accepted[0]).not.toHaveProperty('team_stats');});
it.each(['players-withheld','team-identity','points'])('still withholds unsafe player module %s',kind=>{const raw=body();if(kind==='players-withheld')raw.meta.withheld.players=1;if(kind==='team-identity')raw.data.team_stats[0].team_name='Detroit Pistons';if(kind==='points')Reflect.set(raw.data.players[0].stats,'points',{value:'91'});const c=client(raw);return recoverFinalsSample(schedule,c.value,new Set()).then(r=>{expect(r.accepted).toEqual([]);expect(r.rejected).toHaveLength(1);});});
it('never replaces an existing stronger or accepted snapshot',async()=>{const c=client();expect(await recoverFinalsSample(schedule,c.value,new Set(['0042500405']))).toMatchObject({requests:0,accepted:[],rejected:[]});expect(c.fetcher).not.toHaveBeenCalled();});
it('fails closed if the previously validated schedule identity changes',async()=>{const changed=structuredClone(schedule);for(const day of changed.dates)for(const game of day.games)if(game.gameId==='0042500405')game.homeTeam.score++;const c=client();await expect(recoverFinalsSample(changed,c.value,new Set())).rejects.toThrow('identity changed');expect(c.fetcher).not.toHaveBeenCalled();});

it('never reassigns a provider UUID already saved for another NBA game',async()=>{const c=client();await expect(recoverFinalsSample(schedule,c.value,new Set(),new Map([[VERIFIED_FINALS_SAMPLE.providerMatchId,'0022500340']]))).rejects.toThrow('already assigned');expect(c.fetcher).not.toHaveBeenCalled();});
