import{expect,it,vi}from'vitest';
import{calculateRecoveryRunBudget,RECOVERY_FIRST_PILOT,RECOVERY_METADATA_DIAGNOSTIC,RECOVERY_FINALS_RESTORE,RECOVERY_WORKFLOW_PATH,type RecoveryRunBudgetInput,type RecoveryRunRecord}from'./recovery-run-budget';
import{readRecoveryRunLedger,RECOVERY_REPOSITORY}from'./recovery-github-ledger';
const now='2026-10-02T13:00:00Z';
const current:RecoveryRunRecord={id:99,runAttempt:1,repository:RECOVERY_REPOSITORY,workflowPath:RECOVERY_WORKFLOW_PATH,status:'in_progress',conclusion:null,createdAt:now,startedAt:now,updatedAt:now};
const proof={source:'complete-github-job-metadata',runId:RECOVERY_FIRST_PILOT.runId,jobId:RECOVERY_FIRST_PILOT.jobId,headSha:RECOVERY_FIRST_PILOT.sha,headBranch:'master',event:'push',maxRequests:25,allJobsFetched:true} as const;
const previous:RecoveryRunRecord={...current,id:RECOVERY_FIRST_PILOT.runId,status:'completed',conclusion:'success',createdAt:'2026-10-02T12:26:00Z',startedAt:'2026-10-02T12:26:01Z',updatedAt:'2026-10-02T12:28:00Z',reviewedPilotProof:proof};
function input(prior:RecoveryRunRecord=previous):RecoveryRunBudgetInput{return{now,repository:RECOVERY_REPOSITORY,workflowPath:RECOVERY_WORKFLOW_PATH,currentRun:{id:99,runAttempt:1},ledger:{repository:RECOVERY_REPOSITORY,workflowPath:RECOVERY_WORKFLOW_PATH,complete:true,allPagesFetched:true,totalCount:2,fetchedPages:1,runs:[current,prior]}};}
it('reserves the immutable codebound25 plus knownmanual7, before standalone2 deduction',()=>expect(calculateRecoveryRunBudget(input())).toMatchObject({allowed:true,maxRequests:198,priorReservedRequests:25,knownManualRequests:7}));
it.each([{headSha:'other'},{jobId:1},{event:'workflow_dispatch'},{maxRequests:3},{allJobsFetched:false}])('rejects malformed bounded proof%j',change=>expect(calculateRecoveryRunBudget(input({...previous,reviewedPilotProof:{...proof,...change} as typeof proof}))).toMatchObject({allowed:false}));
it.each([{runAttempt:2},{status:'in_progress',conclusion:null},{id:1},{conclusion:'failure'}])('never refunds an uncertain run%j',change=>expect(calculateRecoveryRunBudget(input({...previous,...change}))).toMatchObject({allowed:false}));
it('absence of bound keeps conservative100 even for previously observed runID',()=>{const raw={...previous};delete raw.reviewedPilotProof;expect(calculateRecoveryRunBudget(input(raw))).toMatchObject({allowed:false});});
function rawRun(r:RecoveryRunRecord){return{id:r.id,run_attempt:r.runAttempt,workflow_id:5,repository:{full_name:r.repository},status:r.status,conclusion:r.conclusion,created_at:r.createdAt,run_started_at:r.startedAt,updated_at:r.updatedAt,head_sha:RECOVERY_FIRST_PILOT.sha,head_branch:'master',event:'push'};}
it('only exact successful live job evidence creates bound and excludes known pilot from unknown-push replay guard',async()=>{const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),rawRun(previous)]}).mockResolvedValueOnce({total_count:1,jobs:[{id:RECOVERY_FIRST_PILOT.jobId,run_id:previous.id,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:'Fetch and normalize provider data',status:'completed',conclusion:'success'}]}]});const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(false);expect(calculateRecoveryRunBudget(result.input)).toMatchObject({allowed:true,maxRequests:198});}});
it('skipped fetch cannot establish bounded execution proof',async()=>{const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),rawRun(previous)]}).mockResolvedValueOnce({total_count:1,jobs:[{id:RECOVERY_FIRST_PILOT.jobId,run_id:previous.id,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:'Fetch and normalize provider data',status:'completed',conclusion:'skipped'}]}]});const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(true);expect(calculateRecoveryRunBudget(result.input)).toMatchObject({allowed:false});}});

it('both exact reviewed bounds reserve25+3, not arbitrary reported usage',()=>{const diagnostic:RecoveryRunRecord={...previous,id:RECOVERY_METADATA_DIAGNOSTIC.runId,reviewedPilotProof:{...proof,runId:RECOVERY_METADATA_DIAGNOSTIC.runId,jobId:RECOVERY_METADATA_DIAGNOSTIC.jobId,headSha:RECOVERY_METADATA_DIAGNOSTIC.sha,maxRequests:3}};const value=input();value.ledger.runs.push(diagnostic);value.ledger.totalCount++;expect(calculateRecoveryRunBudget(value)).toMatchObject({allowed:true,maxRequests:195,priorReservedRequests:28,knownManualRequests:7});});
it('the diagnostic proof requires its own exact success step and SHA',async()=>{const diagnostic={...rawRun(previous),id:RECOVERY_METADATA_DIAGNOSTIC.runId,head_sha:RECOVERY_METADATA_DIAGNOSTIC.sha};const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),diagnostic]}).mockResolvedValueOnce({total_count:1,jobs:[{id:RECOVERY_METADATA_DIAGNOSTIC.jobId,run_id:diagnostic.id,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:'Diagnose one playoff metadata response',status:'completed',conclusion:'success'}]}]});const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(false);expect(calculateRecoveryRunBudget(result.input)).toMatchObject({allowed:true,priorReservedRequests:3});}});

it('all three exact reviewed bounds leave194 before standalone2 deduction',()=>{const value=input();for(const fixed of[RECOVERY_METADATA_DIAGNOSTIC,RECOVERY_FINALS_RESTORE])value.ledger.runs.push({...previous,id:fixed.runId,reviewedPilotProof:{...proof,runId:fixed.runId,jobId:fixed.jobId,headSha:fixed.sha,maxRequests:fixed.maxRequests}});value.ledger.totalCount=value.ledger.runs.length;expect(calculateRecoveryRunBudget(value)).toMatchObject({allowed:true,maxRequests:194,priorReservedRequests:29,knownManualRequests:7});});
it.each([true,false])('restore adapter accepts only the exact successful restore step: %s',async correct=>{const restore={...rawRun(previous),id:RECOVERY_FINALS_RESTORE.runId,head_sha:RECOVERY_FINALS_RESTORE.sha};const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),restore]}).mockResolvedValueOnce({total_count:1,jobs:[{id:RECOVERY_FINALS_RESTORE.jobId,run_id:restore.id,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:correct?'Restore one validated Finals player table':'Fetch and normalize provider data',status:'completed',conclusion:'success'}]}]});const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(!correct);expect(calculateRecoveryRunBudget(result.input)).toMatchObject(correct?{allowed:true,priorReservedRequests:1}:{allowed:false});}});
