import{expect,it,vi}from'vitest';
import{calculateRecoveryRunBudget,RECOVERY_FIRST_PILOT,RECOVERY_METADATA_DIAGNOSTIC,RECOVERY_FINALS_RESTORE,RECOVERY_PLAYOFF_BATCH,RECOVERY_PLAYOFF_BATCH_40,RECOVERY_MEMBERSHIP_DIAGNOSTIC,RECOVERY_REVIEWED_RUNS,RECOVERY_WORKFLOW_PATH,type RecoveryRunBudgetInput,type RecoveryRunRecord}from'./recovery-run-budget';
import{readRecoveryRunLedger,RECOVERY_REPOSITORY}from'./recovery-github-ledger';
const now='2026-10-02T20:30:00Z';
const jobBinding=(id:number)=>({run_attempt:1,head_sha:String(RECOVERY_REVIEWED_RUNS.find(row=>row.jobId===id)!.sha),head_branch:'master'});
const current:RecoveryRunRecord={id:99,runAttempt:1,repository:RECOVERY_REPOSITORY,workflowPath:RECOVERY_WORKFLOW_PATH,status:'in_progress',conclusion:null,createdAt:now,startedAt:now,updatedAt:now};
const proof={source:'complete-github-job-metadata',runId:RECOVERY_FIRST_PILOT.runId,jobId:RECOVERY_FIRST_PILOT.jobId,headSha:RECOVERY_FIRST_PILOT.sha,headBranch:'master',event:'push',maxRequests:25,allJobsFetched:true} as const;
const previous:RecoveryRunRecord={...current,id:RECOVERY_FIRST_PILOT.runId,status:'completed',conclusion:'success',createdAt:'2026-10-02T12:26:00Z',startedAt:'2026-10-02T12:26:01Z',updatedAt:'2026-10-02T12:28:00Z',reviewedPilotProof:proof};
function input(prior:RecoveryRunRecord=previous):RecoveryRunBudgetInput{return{now,repository:RECOVERY_REPOSITORY,workflowPath:RECOVERY_WORKFLOW_PATH,currentRun:{id:99,runAttempt:1},ledger:{repository:RECOVERY_REPOSITORY,workflowPath:RECOVERY_WORKFLOW_PATH,complete:true,allPagesFetched:true,totalCount:2,fetchedPages:1,runs:[current,prior]}};}
it('reserves the immutable codebound25 plus knownmanual7, before standalone2 deduction',()=>expect(calculateRecoveryRunBudget(input())).toMatchObject({allowed:true,maxRequests:198,priorReservedRequests:25,knownManualRequests:7}));
it.each([{headSha:'other'},{jobId:1},{event:'workflow_dispatch'},{maxRequests:3},{allJobsFetched:false}])('rejects malformed bounded proof%j',change=>expect(calculateRecoveryRunBudget(input({...previous,reviewedPilotProof:{...proof,...change} as typeof proof}))).toMatchObject({allowed:false}));
it.each([{runAttempt:2},{status:'in_progress',conclusion:null},{id:1},{conclusion:'failure'}])('never refunds an uncertain run%j',change=>expect(calculateRecoveryRunBudget(input({...previous,...change}))).toMatchObject({allowed:false}));
it('absence of bound keeps conservative100 even for previously observed runID',()=>{const raw={...previous};delete raw.reviewedPilotProof;expect(calculateRecoveryRunBudget(input(raw))).toMatchObject({allowed:false});});
function rawRun(r:RecoveryRunRecord){return{id:r.id,run_attempt:r.runAttempt,workflow_id:5,repository:{full_name:r.repository},status:r.status,conclusion:r.conclusion,created_at:r.createdAt,run_started_at:r.startedAt,updated_at:r.updatedAt,head_sha:RECOVERY_FIRST_PILOT.sha,head_branch:'master',event:'push'};}
it('only exact successful live job evidence creates bound and excludes known pilot from unknown-push replay guard',async()=>{const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),rawRun(previous)]}).mockResolvedValueOnce({total_count:1,jobs:[{...jobBinding(RECOVERY_FIRST_PILOT.jobId),id:RECOVERY_FIRST_PILOT.jobId,run_id:previous.id,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:'Fetch and normalize provider data',status:'completed',conclusion:'success'}]}]});const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(false);expect(calculateRecoveryRunBudget(result.input)).toMatchObject({allowed:true,maxRequests:198});}});
it('skipped fetch cannot establish bounded execution proof',async()=>{const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),rawRun(previous)]}).mockResolvedValueOnce({total_count:1,jobs:[{...jobBinding(RECOVERY_FIRST_PILOT.jobId),id:RECOVERY_FIRST_PILOT.jobId,run_id:previous.id,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:'Fetch and normalize provider data',status:'completed',conclusion:'skipped'}]}]});const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(true);expect(calculateRecoveryRunBudget(result.input)).toMatchObject({allowed:false});}});

it('both exact reviewed bounds reserve25+3, not arbitrary reported usage',()=>{const diagnostic:RecoveryRunRecord={...previous,id:RECOVERY_METADATA_DIAGNOSTIC.runId,reviewedPilotProof:{...proof,runId:RECOVERY_METADATA_DIAGNOSTIC.runId,jobId:RECOVERY_METADATA_DIAGNOSTIC.jobId,headSha:RECOVERY_METADATA_DIAGNOSTIC.sha,maxRequests:3}};const value=input();value.ledger.runs.push(diagnostic);value.ledger.totalCount++;expect(calculateRecoveryRunBudget(value)).toMatchObject({allowed:true,maxRequests:195,priorReservedRequests:28,knownManualRequests:7});});
it('the diagnostic proof requires its own exact success step and SHA',async()=>{const diagnostic={...rawRun(previous),id:RECOVERY_METADATA_DIAGNOSTIC.runId,head_sha:RECOVERY_METADATA_DIAGNOSTIC.sha};const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),diagnostic]}).mockResolvedValueOnce({total_count:1,jobs:[{...jobBinding(RECOVERY_METADATA_DIAGNOSTIC.jobId),id:RECOVERY_METADATA_DIAGNOSTIC.jobId,run_id:diagnostic.id,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:'Diagnose one playoff metadata response',status:'completed',conclusion:'success'}]}]});const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(false);expect(calculateRecoveryRunBudget(result.input)).toMatchObject({allowed:true,priorReservedRequests:3});}});

it('all three exact reviewed bounds leave194 before standalone2 deduction',()=>{const value=input();for(const fixed of[RECOVERY_METADATA_DIAGNOSTIC,RECOVERY_FINALS_RESTORE])value.ledger.runs.push({...previous,id:fixed.runId,reviewedPilotProof:{...proof,runId:fixed.runId,jobId:fixed.jobId,headSha:fixed.sha,maxRequests:fixed.maxRequests}});value.ledger.totalCount=value.ledger.runs.length;expect(calculateRecoveryRunBudget(value)).toMatchObject({allowed:true,maxRequests:194,priorReservedRequests:29,knownManualRequests:7});});
it.each([true,false])('restore adapter accepts only the exact successful restore step: %s',async correct=>{const restore={...rawRun(previous),id:RECOVERY_FINALS_RESTORE.runId,head_sha:RECOVERY_FINALS_RESTORE.sha};const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),restore]}).mockResolvedValueOnce({total_count:1,jobs:[{...jobBinding(RECOVERY_FINALS_RESTORE.jobId),id:RECOVERY_FINALS_RESTORE.jobId,run_id:restore.id,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:correct?'Restore one validated Finals player table':'Fetch and normalize provider data',status:'completed',conclusion:'success'}]}]});const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(!correct);expect(calculateRecoveryRunBudget(result.input)).toMatchObject(correct?{allowed:true,priorReservedRequests:1}:{allowed:false});}});

it('reviewed60 batch leaves132 after standalone2, without refunding to the observed46',()=>{const value=input();for(const fixed of[RECOVERY_METADATA_DIAGNOSTIC,RECOVERY_FINALS_RESTORE,RECOVERY_PLAYOFF_BATCH])value.ledger.runs.push({...previous,id:fixed.runId,reviewedPilotProof:{...proof,runId:fixed.runId,jobId:fixed.jobId,headSha:fixed.sha,maxRequests:fixed.maxRequests}});value.ledger.totalCount=value.ledger.runs.length;expect(calculateRecoveryRunBudget(value)).toMatchObject({allowed:true,maxRequests:134,priorReservedRequests:89,knownManualRequests:7});});
it('reviewed60 batch adapter requires exact source and successful fetch step',async()=>{const batch={...rawRun(previous),id:RECOVERY_PLAYOFF_BATCH.runId,head_sha:RECOVERY_PLAYOFF_BATCH.sha};const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),batch]}).mockResolvedValueOnce({total_count:1,jobs:[{...jobBinding(RECOVERY_PLAYOFF_BATCH.jobId),id:RECOVERY_PLAYOFF_BATCH.jobId,run_id:batch.id,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:'Fetch and normalize provider data',status:'completed',conclusion:'success'}]}]});const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(false);expect(calculateRecoveryRunBudget(result.input)).toMatchObject({allowed:true,priorReservedRequests:60});}});

it('all five reviewed bounds reserve209 and leave12 after standalone2, not a refund to observed57',()=>{const value=input();for(const fixed of[RECOVERY_METADATA_DIAGNOSTIC,RECOVERY_FINALS_RESTORE,RECOVERY_PLAYOFF_BATCH,RECOVERY_PLAYOFF_BATCH_40])value.ledger.runs.push({...previous,id:fixed.runId,reviewedPilotProof:{...proof,runId:fixed.runId,jobId:fixed.jobId,headSha:fixed.sha,maxRequests:fixed.maxRequests}});value.ledger.totalCount=value.ledger.runs.length;expect(calculateRecoveryRunBudget(value)).toMatchObject({allowed:true,maxRequests:14,priorReservedRequests:209,knownManualRequests:7});});
it.each(['valid','wrong-id','wrong-sha','wrong-branch','wrong-attempt','failed-step','wrong-step','truncated'])('120-bound adapter requires complete exact run/job/step evidence: %s',async kind=>{
 const fixed=RECOVERY_PLAYOFF_BATCH_40;const batch={...rawRun(previous),id:fixed.runId,head_sha:fixed.sha};
 const job={...jobBinding(fixed.jobId),id:fixed.jobId as number,run_id:fixed.runId,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:'Fetch and normalize provider data',status:'completed',conclusion:'success'}]};
 if(kind==='wrong-id')job.id=123;if(kind==='wrong-sha')job.head_sha='b'.repeat(40);if(kind==='wrong-branch')job.head_branch='dev';if(kind==='wrong-attempt')job.run_attempt=2;if(kind==='failed-step')job.steps[0].conclusion='failure';if(kind==='wrong-step')job.steps[0].name='other';
 const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),batch]}).mockResolvedValueOnce({total_count:kind==='truncated'?2:1,jobs:[job]}).mockResolvedValueOnce({total_count:2,jobs:[]});
 const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);
 if(kind==='truncated'){expect(result.ok).toBe(false);return;}
 expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(kind!=='valid');expect(calculateRecoveryRunBudget(result.input)).toMatchObject(kind==='valid'?{allowed:true,priorReservedRequests:120,maxRequests:103}:{allowed:false});}
});
it('a 120 proof cannot substitute observed57 usage',()=>{const fixed=RECOVERY_PLAYOFF_BATCH_40;expect(calculateRecoveryRunBudget(input({...previous,id:fixed.runId,reviewedPilotProof:{...proof,runId:fixed.runId,jobId:fixed.jobId,headSha:fixed.sha,maxRequests:57 as 120}}))).toMatchObject({allowed:false});});


it('all six reviewed bounds reserve212 and leave9 after standalone2, without refunding the membership404 call',()=>{
 const value=input();
 for(const fixed of [RECOVERY_METADATA_DIAGNOSTIC,RECOVERY_FINALS_RESTORE,RECOVERY_PLAYOFF_BATCH,RECOVERY_PLAYOFF_BATCH_40,RECOVERY_MEMBERSHIP_DIAGNOSTIC])value.ledger.runs.push({...previous,id:fixed.runId,reviewedPilotProof:{...proof,runId:fixed.runId,jobId:fixed.jobId,headSha:fixed.sha,maxRequests:fixed.maxRequests}});
 value.ledger.totalCount=value.ledger.runs.length;
 expect(calculateRecoveryRunBudget(value)).toMatchObject({allowed:true,maxRequests:11,priorReservedRequests:212,knownManualRequests:7});
});
it.each(['valid','wrong-id','wrong-sha','wrong-branch','wrong-attempt','failed-step','wrong-step','truncated'])('membership3 bound requires complete exact immutable run/job/step evidence: %s',async kind=>{
 const fixed=RECOVERY_MEMBERSHIP_DIAGNOSTIC;const batch={...rawRun(previous),id:fixed.runId,head_sha:fixed.sha};
 const job={...jobBinding(fixed.jobId),id:fixed.jobId as number,run_id:fixed.runId,name:'Ingest player data',status:'completed',conclusion:'success',steps:[{name:'Diagnose fixed NBA game membership',status:'completed',conclusion:'success'}]};
 if(kind==='wrong-id')job.id=123;if(kind==='wrong-sha')job.head_sha='b'.repeat(40);if(kind==='wrong-branch')job.head_branch='dev';if(kind==='wrong-attempt')job.run_attempt=2;if(kind==='failed-step')job.steps[0].conclusion='failure';if(kind==='wrong-step')job.steps[0].name='Fetch and normalize provider data';
 const get=vi.fn().mockResolvedValueOnce({id:5,path:RECOVERY_WORKFLOW_PATH}).mockResolvedValueOnce({total_count:2,workflow_runs:[rawRun(current),batch]}).mockResolvedValueOnce({total_count:kind==='truncated'?2:1,jobs:[job]}).mockResolvedValueOnce({total_count:2,jobs:[]});
 const result=await readRecoveryRunLedger(get,{id:99,runAttempt:1},now);
 if(kind==='truncated'){expect(result.ok).toBe(false);return;}
 expect(result.ok).toBe(true);if(result.ok){expect(result.priorPushRun).toBe(kind!=='valid');expect(calculateRecoveryRunBudget(result.input)).toMatchObject(kind==='valid'?{allowed:true,priorReservedRequests:3,maxRequests:220}:{allowed:false});}
});
it('membership proof cannot substitute the observed one request for its immutable three-call bound',()=>{
 const fixed=RECOVERY_MEMBERSHIP_DIAGNOSTIC;
 expect(calculateRecoveryRunBudget(input({...previous,id:fixed.runId,reviewedPilotProof:{...proof,runId:fixed.runId,jobId:fixed.jobId,headSha:fixed.sha,maxRequests:1}}))).toMatchObject({allowed:false});
});
