import{expect,it,vi}from'vitest';
import archived from '../data/recovered-player-boxes.json';
import listExcerpt from './fixtures/bigballs-list-actual-excerpt.json';
import{runRecoveryBatch}from'./recovery-batch';
import{createRecoveryProviderClient}from'./recovery-provider-client';
import{validateProviderPlayerSnapshot}from'./provider-player-snapshot';
import type{RecoveryTarget}from'./recovery-candidates';
const box=archived['0022500340'];
const target:RecoveryTarget={nbaGameId:box.gameId,season:box.season,gameDate:box.gameDate,home:{tricode:box.home,score:box.homeScore},away:{tricode:box.away,score:box.awayScore},lookupDates:['2025-12-05','2025-12-06']};
// Synthetic complete TEST envelopes, rebuilt from the captured field schema and
// verified player scalars. They are not full real HTTP-response captures.
const stats=()=>({meta:{available:true,players_available:true,team_stats_available:true,withheld:{players:0,team_stats:0}},data:{team_stats:[{team_name:'Atlanta Hawks'},{team_name:'Denver Nuggets'}],players:box.players.map(p=>({name:p.name,team_name:'UNTRUSTED CURRENT TEAM',stats:{...Object.fromEntries(['points','rebounds','assists','offensiveRebounds','defensiveRebounds','steals','blocks','turnovers','fouls','plusMinus','minutes','starter'].map(k=>[k,{value:String(p[k as keyof typeof p])}])),'fieldGoalsMade-fieldGoalsAttempted':{value:`${p.fieldGoalsMade}-${p.fieldGoalsAttempted}`},'threePointFieldGoalsMade-threePointFieldGoalsAttem':{value:`${p.threePointersMade}-${p.threePointersAttempted}`},'freeThrowsMade-freeThrowsAttempted':{value:`${p.freeThrowsMade}-${p.freeThrowsAttempted}`}}}))}});
function fetcher(){return vi.fn(async(url:string|URL|Request)=>{const u=new URL(String(url));let body:unknown;if(u.pathname.endsWith('/stats'))body=stats();else{const date=u.searchParams.get('date')!;body={...listExcerpt.response,data:date==='2025-12-05'?listExcerpt.response.data:[],meta:{date_window:{date}},pagination:{offset:0,limit:100,total:date==='2025-12-05'?1:0}};}return new Response(JSON.stringify(body));});}
const client=(f:ReturnType<typeof fetcher>,max=3)=>createRecoveryProviderClient({apiKey:'TEST_ONLY',maxRequests:max,expiresAt:'2026-10-03T00:00:00Z',now:()=>Date.parse('2026-10-02T03:17:00Z'),fetcher:f});
it('offlineendtoend uses twocomplete datepages andone statsrequest toproducevalidatedunassignedsnapshot',async()=>{const f=fetcher();const result=await runRecoveryBatch([target],client(f),3,new Set());expect(result.requests).toBe(3);expect(result.accepted).toHaveLength(1);expect(result.accepted[0].players).toHaveLength(19);expect(result.accepted[0].players.find(p=>p.name==='Nikola Jokic')).toMatchObject({points:40,rebounds:9,assists:8,team:null});expect(validateProviderPlayerSnapshot(result.accepted[0])).not.toBeNull();expect(result.rejected).toHaveLength(0);expect(result.cursor).toBe(target.nbaGameId);});
it('budgetexhaustionwithholdsdata ratherthanissuinganextra statsrequest',async()=>{const f=fetcher();const result=await runRecoveryBatch([target],client(f,2),2,new Set());expect(f).toHaveBeenCalledTimes(2);expect(result.requests).toBe(2);expect(result.accepted).toHaveLength(0);expect(result.rejected).toHaveLength(1);expect(result.cursor).toBeNull();expect(result.rejected[0].reason).toBe('provider-stats-budget-or-deadline-exhausted');});
it('previouslyassignedprovideridentity cannotbeassignedtoanotherNBAgame',async()=>{const f=fetcher();const result=await runRecoveryBatch([target],client(f),3,new Set(),new Map([[box.providerMatchId,'0022500999']]));expect(f).toHaveBeenCalledTimes(2);expect(result.accepted).toHaveLength(0);expect(result.rejected[0].reason).toBe('provider-match-already-assigned');});
it('anactuallytruncatedlistcannotestablishuniqueidentity',async()=>{const f=vi.fn().mockResolvedValue(new Response(JSON.stringify(listExcerpt.response)));const one={...target,lookupDates:['2025-12-05']};const result=await runRecoveryBatch([one],client(f),3,new Set());expect(result.accepted).toHaveLength(0);expect(f).toHaveBeenCalledTimes(1);});

it('transportfailure retains the previous cursor so an interrupted target is retryable',async()=>{const f=vi.fn().mockResolvedValue(new Response('unavailable',{status:503}));const result=await runRecoveryBatch([target],client(f),3,new Set());expect(result.cursor).toBeNull();expect(result.rejected[0]).toEqual({gameId:target.nbaGameId,reason:'provider-list-provider-unavailable-http-503'});});
