import { expect, it } from 'vitest';
import archive from '../data/schedule-2025-26.json';
import { planCurrentRecovery, readObservedRetries, updateObservedRetries } from './recovery-current-queue';
import { OFFICIAL_RECOVERY_SCHEDULE_URL, projectOfficialRecoverySchedule, type OfficialScheduleResult } from './recovery-official-schedule';
import type { ObservedFinalGame } from './observed-final-game';
const now='2026-10-26T12:00:00.000Z';
function observation(index=1,season='2026-27'):ObservedFinalGame {
 const year=Number(season.slice(0,4)),day=String(1+index%24).padStart(2,'0');
 const result=projectOfficialRecoverySchedule({leagueSchedule:{seasonYear:season,gameDates:[{games:[{
  gameId:`002${season.slice(2,4)}${String(index).padStart(5,'0')}`,gameStatus:3,gameCode:`${year}10${day}/NYKSAS`,gameDateTimeUTC:`${year}-10-${day}T00:30:00Z`,
  homeTeam:{teamId:1610612759,teamTricode:'SAS',score:90+index},awayTeam:{teamId:1610612752,teamTricode:'NYK',score:94+index}
 }]}]}},{expectedSeason:season,now,source:{url:OFFICIAL_RECOVERY_SCHEDULE_URL,sha256:'a'.repeat(64),observedAt:now}});
 if(result.status!=='ready')throw Error('Invalid queue fixture');return{version:1,game:result.games[0],source:result.source};
}
function discovery(rows=[observation()]):OfficialScheduleResult{return{status:rows.length?'ready':'empty',season:'2026-27',games:rows.map(row=>row.game),source:observation().source};}
const input=()=>({archive,observed:{},discovery:discovery(),currentSeason:'2026-27',existingIds:new Set<string>(),historicalCursor:null,retries:{},now});
it('prioritizes current observed finals ahead of historical Finals without relabeling either season',()=>{const plan=planCurrentRecovery(input());expect(plan.targets).toHaveLength(20);expect(plan.targets[0]).toMatchObject({nbaGameId:'0022600001',season:'2026-27'});expect(plan.targets[1].season).toBe('2025-26');expect(plan.targets[1].nbaGameId.startsWith('00425004')).toBe(true);});
it('never selects more than twenty targets or observations even with thirty unseen finals',()=>{const plan=planCurrentRecovery({...input(),discovery:discovery(Array.from({length:30},(_,i)=>observation(i+1)))});expect(plan.targets).toHaveLength(20);expect(plan.observations).toHaveLength(20);expect(plan.historicalIds.size).toBe(0);});
it.each(['missing','unavailable','malformed','stale','wrong-season'] as const)('keeps known current identities retryable when new source is %s',status=>{const row=observation();const plan=planCurrentRecovery({...input(),observed:{[row.game.nbaGameId]:row},discovery:{status,reason:'fixture'}});expect(plan.targets[0].nbaGameId).toBe(row.game.nbaGameId);expect(plan.newObservationCount).toBe(0);});
it('empty discovery retains saved identities and does not remove history',()=>{const row=observation();const plan=planCurrentRecovery({...input(),observed:{[row.game.nbaGameId]:row},discovery:discovery([])});expect(plan.observations).toEqual([row]);expect(plan.targets).toHaveLength(20);});
it('skips already archived snapshots without refetching them',()=>{const plan=planCurrentRecovery({...input(),existingIds:new Set(['0022600001'])});expect(plan.targets.some(t=>t.nbaGameId==='0022600001')).toBe(false);});
it('does not overwrite an existing tuple when source changes score',()=>{const row=observation(),changed=observation();changed.game.home.score++;const plan=planCurrentRecovery({...input(),observed:{[row.game.nbaGameId]:row},discovery:discovery([changed])});expect(plan.conflicts).toEqual([row.game.nbaGameId]);expect(plan.observations).toEqual([]);expect(row.game.home.score).toBe(91);});
it('ambiguous adjacent-day lookup identities are withheld',()=>{const a=observation(),b=observation();b.game.nbaGameId='0022609999';const plan=planCurrentRecovery({...input(),discovery:discovery([a,b])});expect(plan.observations).toEqual([]);});
it('older observed records remain eligible after rollover but current results precede them',()=>{const old=observation(1,'2025-26');const plan=planCurrentRecovery({...input(),observed:{[old.game.nbaGameId]:old}});expect(plan.targets.slice(0,2).map(t=>t.season)).toEqual(['2026-27','2025-26']);});
it('applies a bounded failure cooldown and reopens exactly at its boundary',()=>{const retries={'0022600001':{retryAfter:'2026-10-28T12:00:00.000Z',reason:'missing-data'}};expect(planCurrentRecovery({...input(),retries}).observations).toEqual([]);expect(planCurrentRecovery({...input(),retries,now:retries['0022600001'].retryAfter}).observations).toHaveLength(1);});
it('records classified errors without cooling an interrupted transport target',()=>{const result={accepted:[],rejected:[{gameId:'0022600001',reason:'invalid-player'},{gameId:'0022600002',reason:'provider-list-network-or-budget'}],cursor:'0022600001',interrupted:true};expect(updateObservedRetries({},result,new Set(['0022600001','0022600002']),new Set(),now)).toEqual({'0022600001':{retryAfter:'2026-10-28T12:00:00.000Z',reason:'invalid-player'}});});
it('budget exhaustion before next target does not erase cooldown for the last classified rejection',()=>{const result={accepted:[],rejected:[{gameId:'0022600001',reason:'invalid-player'}],cursor:'0022600001',interrupted:true};expect(updateObservedRetries({},result,new Set(['0022600001']),new Set(),now)).toHaveProperty('0022600001');});
it('successful saves clear retry state while unrelated legacy rejections never enter it',()=>{const previous={'0022600001':{retryAfter:now,reason:'missing-data'}};expect(updateObservedRetries(previous,{accepted:[{game:{nbaGameId:'0022600001'}}],rejected:[{gameId:'0042500405',reason:'invalid-player'}]},new Set(['0022600001']),new Set(),now)).toEqual({});});
it.each([null,[],{'0022600001':{retryAfter:'bad',reason:'test'}},{'0022600001':{retryAfter:now,reason:'RAW text/secret'}},{'bad':{retryAfter:now,reason:'test'}}])('invalid retry state fails closed',raw=>expect(()=>readObservedRetries(raw)).toThrow());
it('old version state without retries is valid and source season mismatch fails closed',()=>{expect(readObservedRetries(undefined)).toEqual({});expect(()=>planCurrentRecovery({...input(),discovery:{...discovery(),season:'2025-26'} as OfficialScheduleResult})).toThrow('season mismatch');});
