// Frozen 2025-26 end-of-season data, generated by scripts/snapshot-season.mjs
// while the single-season CDN schedule doc still carried 2025-26. Served as
// fallback by /api/standings and the follow digest during the offseason
// window after the feed rolls to the new season (zero finished games).
import snapshotJson from "@/data/season-2025-26-final.json";

export interface SnapshotTeam {
  tricode: string;
  teamId: number;
  teamName: string;
  teamCity: string;
  wins: number;
  losses: number;
}

export interface SnapshotGame {
  gameId: string;
  /** ET calendar date, YYYY-MM-DD */
  gameDate: string;
  homeTricode: string;
  homeTeamId: number;
  homeScore: number;
  awayTricode: string;
  awayTeamId: number;
  awayScore: number;
}

export interface SeasonSnapshot {
  season: string;
  generatedAt: string;
  /** sorted by win% desc — same order /api/standings emits */
  teams: SnapshotTeam[];
  /** ALL finished games incl. playoffs, chronological */
  finishedGames: SnapshotGame[];
}

export const SEASON_SNAPSHOT: SeasonSnapshot = snapshotJson;

export interface StandingsPayload {
  data: SnapshotTeam[];
  archived?: boolean;
  season?: string;
}

/** Live standings pass through untouched; an empty table (rolled-over feed)
 *  swaps in the archived snapshot, flagged so the UI can label it. */
export function standingsPayload(
  live: SnapshotTeam[],
  snapshot: SeasonSnapshot = SEASON_SNAPSHOT,
): StandingsPayload {
  if (live.length > 0) return { data: live };
  return { data: snapshot.teams, archived: true, season: snapshot.season };
}
